// ============================================================
// UBG PRO — GAME LIBRARY
// Curated list of working games (NO crazygames URLs).
// Sources: direct .io domains, gameflare.com /embed/, lichess.org,
// classic.minecraft.net, nytimes wordle, play2048, sandboxels, etc.
// ============================================================

const _thumb = (name) =>
  "https://tse2.mm.bing.net/th?q=" +
  encodeURIComponent(name + " game thumbnail") +
  "&w=320&h=200&c=7";

const _GAMES_RAW = [
  // ---- IO MULTIPLAYER / SHOOTERS (direct .io domains) ----
  { id: 1,  name: "Slither.io",          cat: "multiplayer", emoji: "🐍",  url: "https://slither.io/",                   featured: true  },
  { id: 2,  name: "Agar.io",             cat: "multiplayer", emoji: "🔵",  url: "https://agar.io/"                                           },
  { id: 3,  name: "Diep.io",             cat: "multiplayer", emoji: "🪖",  url: "https://diep.io/",                      featured: true  },
  { id: 4,  name: "Krunker.io",          cat: "shooting",    emoji: "🔫",  url: "https://krunker.io/",                   featured: true  },
  { id: 5,  name: "Shell Shockers",      cat: "shooting",    emoji: "🥚",  url: "https://shellshock.io/",                featured: true  },
  { id: 6,  name: "Venge.io",            cat: "shooting",    emoji: "🎯",  url: "https://venge.io/"                                          },
  { id: 7,  name: "1v1.LOL",             cat: "shooting",    emoji: "🏗️", url: "https://1v1.lol/",                      featured: true  },
  { id: 8,  name: "Bonk.io",             cat: "multiplayer", emoji: "💥",  url: "https://bonk.io/",                                          unity: true },
  { id: 9,  name: "Smash Karts",         cat: "racing",      emoji: "🏎️", url: "https://smashkarts.io/",                featured: true,  unity: true },
  { id: 10, name: "Skribbl.io",          cat: "multiplayer", emoji: "🖌️", url: "https://skribbl.io/"                                        },
  { id: 11, name: "Gartic Phone",        cat: "multiplayer", emoji: "🎨",  url: "https://garticphone.com/"                                   },
  { id: 12, name: "Zombs Royale",        cat: "multiplayer", emoji: "🧟",  url: "https://zombsroyale.io/",               featured: true  },
  { id: 13, name: "Starblast.io",        cat: "multiplayer", emoji: "🚀",  url: "https://starblast.io/"                                      },
  { id: 14, name: "MooMoo.io",           cat: "multiplayer", emoji: "🐮",  url: "https://moomoo.io/"                                         },
  { id: 15, name: "Little Big Snake",    cat: "multiplayer", emoji: "🐉",  url: "https://littlebigsnake.com/"                                },
  { id: 16, name: "Wormate.io",          cat: "multiplayer", emoji: "🪱",  url: "https://wormate.io/"                                        },
  { id: 17, name: "Splix.io",            cat: "multiplayer", emoji: "🟦",  url: "https://splix.io/"                                          },
  { id: 18, name: "Deeeep.io",           cat: "multiplayer", emoji: "🐟",  url: "https://deeeep.io/"                                         },
  { id: 19, name: "Evades.io",           cat: "multiplayer", emoji: "💢",  url: "https://evades.io/"                                         },
  { id: 20, name: "Defly.io",            cat: "multiplayer", emoji: "🚁",  url: "https://defly.io/"                                          },
  { id: 21, name: "Mope.io",             cat: "multiplayer", emoji: "🦊",  url: "https://mope.io/"                                           },
  { id: 22, name: "EV.io",               cat: "shooting",    emoji: "🎮",  url: "https://ev.io/",                        featured: true  },
  { id: 23, name: "Narrow.One",          cat: "shooting",    emoji: "🏹",  url: "https://narrow.one/",                   featured: true,  unity: true },
  { id: 24, name: "GoBattle.io",         cat: "action",      emoji: "⚔️", url: "https://gobattle.io/",                                      unity: true },
  { id: 25, name: "Tribals.io",          cat: "strategy",    emoji: "🏕️", url: "https://tribals.io/",                                       unity: true },
  { id: 26, name: "Foes.io",             cat: "shooting",    emoji: "💀",  url: "https://foes.io/"                                           },
  { id: 27, name: "Doblons.io",          cat: "multiplayer", emoji: "⛵",  url: "https://doblons.io/"                                        },
  { id: 28, name: "Raaaaft.io",          cat: "multiplayer", emoji: "🛟",  url: "https://raaaa.io/"                                          },
  { id: 29, name: "Driftin.io",          cat: "racing",      emoji: "🏁",  url: "https://driftin.io/"                                        },
  { id: 30, name: "Territorial.io",      cat: "strategy",    emoji: "🗺️", url: "https://territorial.io/",               featured: true  },
  { id: 31, name: "Mini Royale 2",       cat: "shooting",    emoji: "👑",  url: "https://miniroyale2.io/",                                   unity: true },
  { id: 32, name: "FlyOrDie.io",         cat: "multiplayer", emoji: "🦅",  url: "https://flyordie.io/"                                       },
  { id: 33, name: "Yorg.io",             cat: "strategy",    emoji: "🛡️", url: "https://yorg.io/"                                           },
  { id: 34, name: "Generals.io",         cat: "strategy",    emoji: "♟️", url: "https://generals.io/"                                       },
  { id: 35, name: "Powerline.io",        cat: "multiplayer", emoji: "⚡",  url: "https://powerline.io/"                                      },
  { id: 36, name: "Wings.io",            cat: "multiplayer", emoji: "✈️", url: "https://wings.io/"                                          },
  { id: 37, name: "Wanderers.io",        cat: "strategy",    emoji: "🧙",  url: "https://wanderers.io/"                                      },
  { id: 38, name: "Arras.io",            cat: "multiplayer", emoji: "🛸",  url: "https://arras.io/"                                          },
  { id: 39, name: "Sploop.io",           cat: "multiplayer", emoji: "🪓",  url: "https://sploop.io/"                                         },
  { id: 40, name: "Gulper.io",           cat: "multiplayer", emoji: "🌀",  url: "https://gulper.io/"                                         },
  { id: 41, name: "Limax.io",            cat: "multiplayer", emoji: "🐌",  url: "https://limax.io/"                                          },
  { id: 42, name: "Snowball.io",         cat: "multiplayer", emoji: "❄️", url: "https://snowball.io/"                                       },
  { id: 43, name: "Zlap.io",             cat: "multiplayer", emoji: "🔨",  url: "https://zlap.io/"                                           },
  { id: 44, name: "Dynast.io",           cat: "multiplayer", emoji: "🏰",  url: "https://dynast.io/"                                         },
  { id: 45, name: "Supersnake.io",       cat: "multiplayer", emoji: "🐍",  url: "https://supersnake.io/"                                     },
  { id: 46, name: "Biteme.io",           cat: "multiplayer", emoji: "🦈",  url: "https://biteme.io/"                                         },
  { id: 47, name: "Swordbattle.io",      cat: "multiplayer", emoji: "🗡️", url: "https://swordbattle.io/"                                    },
  { id: 48, name: "Digdig.io",           cat: "multiplayer", emoji: "⛏️", url: "https://digdig.io/"                                         },
  { id: 49, name: "Spinz.io",            cat: "multiplayer", emoji: "🌪️", url: "https://spinz.io/"                                          },
  { id: 50, name: "Lordz2.io",           cat: "strategy",    emoji: "👑",  url: "https://lordz2.io/"                                         },
  { id: 51, name: "Voxiom.io",           cat: "shooting",    emoji: "🟫",  url: "https://voxiom.io/",                                        unity: true },
  { id: 52, name: "Stabfish.io",         cat: "multiplayer", emoji: "🐡",  url: "https://stabfish.io/"                                       },
  { id: 53, name: "Lordz.io",            cat: "strategy",    emoji: "🏯",  url: "https://www.lordz.io/"                                      },
  { id: 54, name: "Gota.io",             cat: "multiplayer", emoji: "🟣",  url: "https://gota.io/web/"                                       },
  { id: 55, name: "Pixelz.io",           cat: "multiplayer", emoji: "🟪",  url: "https://pixelz.io/"                                         },
  { id: 56, name: "Hexar.io",            cat: "multiplayer", emoji: "⬡",   url: "https://hexar.io/"                                          },
  { id: 57, name: "Hordes.io",           cat: "multiplayer", emoji: "🧝",  url: "https://hordes.io/"                                         },
  { id: 58, name: "Repuls.io",           cat: "shooting",    emoji: "🤖",  url: "https://repuls.io/",                                        unity: true },
  { id: 59, name: "Taming.io",           cat: "multiplayer", emoji: "🐺",  url: "https://taming.io/"                                         },
  { id: 60, name: "Mope2.io",            cat: "multiplayer", emoji: "🦒",  url: "https://mope2.io/"                                          },
  { id: 61, name: "Brutal.io",           cat: "multiplayer", emoji: "⚒️", url: "https://brutal.io/"                                         },
  { id: 62, name: "Curve Fever Pro",     cat: "multiplayer", emoji: "🐍",  url: "https://curvefever.pro/"                                    },
  { id: 63, name: "Junon.io",            cat: "multiplayer", emoji: "🌙",  url: "https://junon.io/"                                          },
  { id: 64, name: "Florr.io",            cat: "multiplayer", emoji: "🌸",  url: "https://florr.io/"                                          },

  // ---- GAMEFLARE EMBEDS (single-player favorites) ----
  { id: 65,  name: "Stickman Hook",        cat: "arcade",      emoji: "🪝",  url: "https://www.gameflare.com/embed/stickman-hook/",            featured: true  },
  { id: 66,  name: "Moto X3M",             cat: "racing",      emoji: "🏍️", url: "https://www.gameflare.com/embed/moto-x3m/",                 featured: true  },
  { id: 67,  name: "Vex 5",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-5/"                                                },
  { id: 68,  name: "Vex 6",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-6/"                                                },
  { id: 69,  name: "Vex 7",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-7/"                                                },
  { id: 70,  name: "Run 3",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/run-3/",                    featured: true  },
  { id: 71,  name: "Tomb Runner",          cat: "adventure",   emoji: "🏛️", url: "https://www.gameflare.com/embed/tomb-runner/"                                          },
  { id: 72,  name: "Short Life",           cat: "arcade",      emoji: "💀",  url: "https://www.gameflare.com/embed/short-life/"                                            },
  { id: 73,  name: "Short Life 2",         cat: "arcade",      emoji: "💀",  url: "https://www.gameflare.com/embed/short-life-2/"                                          },
  { id: 74,  name: "Subway Clash 3D",      cat: "shooting",    emoji: "🚇",  url: "https://www.gameflare.com/embed/subway-clash-3d/"                                        },
  { id: 75,  name: "Madalin Stunt Cars 2", cat: "racing",      emoji: "🚗",  url: "https://www.gameflare.com/embed/madalin-stunt-cars-2/"                                   },
  { id: 76,  name: "Cubes 2048.io",        cat: "puzzle",      emoji: "🟦",  url: "https://www.gameflare.com/embed/cubes-2048-io/"                                          },
  { id: 77,  name: "Bullet Force",         cat: "shooting",    emoji: "🔫",  url: "https://www.gameflare.com/embed/bullet-force/",                                          unity: true },
  { id: 78,  name: "Drift Hunters",        cat: "racing",      emoji: "🏎️", url: "https://www.gameflare.com/embed/drift-hunters/",            featured: true,  unity: true },
  { id: 79,  name: "Stickman Boost",       cat: "arcade",      emoji: "🥷",  url: "https://www.gameflare.com/embed/stickman-boost/"                                         },
  { id: 80,  name: "Master Chess",         cat: "puzzle",      emoji: "♟️", url: "https://www.gameflare.com/embed/master-chess/"                                            },
  { id: 81,  name: "8 Ball Billiards",     cat: "sports",      emoji: "🎱",  url: "https://www.gameflare.com/embed/8-ball-billiards-classic/"                               },
  { id: 82,  name: "Basketball Stars",     cat: "sports",      emoji: "🏀",  url: "https://www.gameflare.com/embed/basketball-stars/"                                       },
  { id: 83,  name: "Soccer Skills",        cat: "sports",      emoji: "⚽",  url: "https://www.gameflare.com/embed/soccer-skills-euro-cup-2021/"                            },
  { id: 84,  name: "Among Us",             cat: "multiplayer", emoji: "🚀",  url: "https://www.gameflare.com/embed/among-us/"                                               },
  { id: 85,  name: "Fall Guys",            cat: "multiplayer", emoji: "🏆",  url: "https://www.gameflare.com/embed/fall-guys/"                                              },
  { id: 86,  name: "Happy Wheels",         cat: "arcade",      emoji: "🚲",  url: "https://www.gameflare.com/embed/happy-wheels/",             featured: true  },
  { id: 87,  name: "Tank Trouble",         cat: "action",      emoji: "🪖",  url: "https://www.gameflare.com/embed/tank-trouble/"                                           },
  { id: 88,  name: "Stickman Fighter",     cat: "action",      emoji: "🥋",  url: "https://www.gameflare.com/embed/stickman-fighter-epic-battle/"                          },
  { id: 89,  name: "Geometry Dash",        cat: "arcade",      emoji: "🔺",  url: "https://www.gameflare.com/embed/geometry-dash/",            featured: true  },
  { id: 90,  name: "Cut the Rope",         cat: "puzzle",      emoji: "✂️", url: "https://www.gameflare.com/embed/cut-the-rope/"                                            },
  { id: 91,  name: "Slope",                cat: "arcade",      emoji: "🟢",  url: "https://www.gameflare.com/embed/slope/",                    featured: true  },
  { id: 92,  name: "Death Run 3D",         cat: "adventure",   emoji: "💀",  url: "https://www.gameflare.com/embed/death-run-3d/"                                           },
  { id: 93,  name: "Tunnel Rush",          cat: "arcade",      emoji: "🌀",  url: "https://www.gameflare.com/embed/tunnel-rush/"                                            },
  { id: 94,  name: "Drift Boss",           cat: "racing",      emoji: "🚙",  url: "https://www.gameflare.com/embed/drift-boss/"                                             },
  { id: 95,  name: "Eggy Car",             cat: "racing",      emoji: "🥚",  url: "https://www.gameflare.com/embed/eggy-car/"                                               },
  { id: 96,  name: "Drive Mad",            cat: "racing",      emoji: "🚛",  url: "https://www.gameflare.com/embed/drive-mad/"                                              },
  { id: 97,  name: "Retro Bowl",           cat: "sports",      emoji: "🏈",  url: "https://www.gameflare.com/embed/retro-bowl/",               featured: true  },
  { id: 98,  name: "Tiny Fishing",         cat: "arcade",      emoji: "🎣",  url: "https://www.gameflare.com/embed/tiny-fishing/"                                           },
  { id: 99,  name: "Idle Breakout",        cat: "arcade",      emoji: "🧱",  url: "https://www.gameflare.com/embed/idle-breakout/"                                          },
  { id: 100, name: "Doodle Jump",          cat: "arcade",      emoji: "🦘",  url: "https://www.gameflare.com/embed/doodle-jump/"                                            },
  { id: 101, name: "Stickman Climb 2",     cat: "arcade",      emoji: "🧗",  url: "https://www.gameflare.com/embed/stickman-climb-2/"                                       },
  { id: 102, name: "Iron Snout",           cat: "action",      emoji: "🐷",  url: "https://www.gameflare.com/embed/iron-snout/"                                             },
  { id: 103, name: "Rooftop Snipers",      cat: "shooting",    emoji: "🎯",  url: "https://www.gameflare.com/embed/rooftop-snipers/"                                        },
  { id: 104, name: "Stick Duel",           cat: "action",      emoji: "⚔️", url: "https://www.gameflare.com/embed/stick-duel-medieval-wars/"                                },
  { id: 105, name: "Getaway Shootout",     cat: "shooting",    emoji: "🚁",  url: "https://www.gameflare.com/embed/getaway-shootout/",                                       unity: true },
  { id: 106, name: "Ragdoll Archers",      cat: "action",      emoji: "🏹",  url: "https://www.gameflare.com/embed/ragdoll-archers/",                                        unity: true },
  { id: 123, name: "Pixel Warfare",        cat: "shooting",    emoji: "💥",  url: "https://www.gameflare.com/embed/pixel-warfare/",                                           unity: true },
  { id: 124, name: "Blocky Cars",          cat: "racing",      emoji: "🚗",  url: "https://www.gameflare.com/embed/blocky-cars/",                                               unity: true },
  { id: 125, name: "War Brokers",          cat: "shooting",    emoji: "🎖️", url: "https://www.warbrokers.io/",                featured: true,  unity: true },
  { id: 126, name: "Copter.io",            cat: "shooting",    emoji: "🚁",  url: "https://copter.io/",                      featured: true,  unity: true },
  { id: 127, name: "Survivor.io",          cat: "multiplayer", emoji: "🧟",  url: "https://survivor.io/",                     featured: true,  unity: true },
  { id: 128, name: "Hole.io",              cat: "multiplayer", emoji: "🕳️", url: "https://hole-io.com/",                     featured: true,  unity: true },
  { id: 129, name: "Paper.io 2",           cat: "multiplayer", emoji: "📄",  url: "https://paper-io.com/paperio2.htm",        featured: true,  unity: true },
  { id: 130, name: "Mini Royale 2",        cat: "shooting",    emoji: "👑",  url: "https://miniroyale2.io/",                                  unity: true },
  { id: 131, name: "Repuls.io",            cat: "shooting",    emoji: "🤖",  url: "https://repuls.io/",                      featured: true,  unity: true },
  { id: 132, name: "Build Royale",         cat: "shooting",    emoji: "🏗️", url: "https://buildroyale.io/",                  featured: true,  unity: true },
  { id: 133, name: "Pixel Gun 3D",         cat: "shooting",    emoji: "🔫",  url: "https://pixelgun3d.net/play/",          featured: true,  unity: true },
  { id: 134, name: "Blockpost",            cat: "shooting",    emoji: "🎯",  url: "https://blockpost.net/",                  featured: true,  unity: true },
  { id: 135, name: "Forward Assault",      cat: "shooting",    emoji: "⚔️", url: "https://forwardassault.io/",              featured: true,  unity: true },

  // ---- STANDALONE / OFFICIAL SITES ----
  { id: 136, name: "Chess (Lichess)",      cat: "puzzle",      emoji: "♟️", url: "https://lichess.org/",                  featured: true  },
  { id: 137, name: "Wordle",               cat: "puzzle",      emoji: "📝",  url: "https://www.nytimes.com/games/wordle/index.html"                                          },
  { id: 138, name: "Minecraft Classic",    cat: "adventure",   emoji: "⛏️", url: "https://classic.minecraft.net/",        featured: true,  unity: true },
  { id: 139, name: "Cookie Clicker",       cat: "strategy",    emoji: "🍪",  url: "https://orteil.dashnet.org/cookieclicker/"                                                },
  { id: 140, name: "2048",                 cat: "puzzle",      emoji: "🔢",  url: "https://play2048.co/"                                                                     },
  { id: 141, name: "Sandboxels",           cat: "puzzle",      emoji: "🧪",  url: "https://sandboxels.r74n.com/"                                                             },
  { id: 142, name: "The Powder Toy",       cat: "puzzle",      emoji: "💨",  url: "https://powdertoy.co.uk/"                                                                 },
  { id: 143, name: "Snake",                cat: "arcade",      emoji: "🐍",  url: "https://playsnake.org/"                                                                   },
  { id: 144, name: "Tetris",               cat: "puzzle",      emoji: "🟦",  url: "https://tetris.com/play-tetris"                                                           },
  { id: 145, name: "GeoGuessr Free",       cat: "puzzle",      emoji: "🌍",  url: "https://www.geoguessr.com/free"                                                           },
  { id: 146, name: "Town of Salem",        cat: "strategy",    emoji: "🕵️", url: "https://www.blankmediagames.com/TownOfSalem/"                                              },
  { id: 147, name: "Sketchful.io",         cat: "multiplayer", emoji: "✏️", url: "https://sketchful.io/"                                                                    },
  { id: 148, name: "Drawasaurus",          cat: "multiplayer", emoji: "🦖",  url: "https://www.drawasaurus.org/"                                                             },
  { id: 149, name: "Super Smash Flash 2",  cat: "action",      emoji: "👊",  url: "https://www.supersmashflash.com/play/ssf2/",                featured: true  },
];

const GAMES = _GAMES_RAW.map((g) => ({ ...g, thumb: _thumb(g.name) }));
