// ============================================================
// UBG PRO — GAME LIBRARY
// Curated list of working games (NO crazygames URLs).
// Sources: direct .io domains, gameflare.com /embed/, lichess.org,
// classic.minecraft.net, nytimes wordle, play2048, sandboxels, etc.
// ============================================================

const _thumb = (name) =>
  "https://tse2.mm.bing.net/th?q=" +
  encodeURIComponent(name + " game thumbnail") +
  "&w=320&h=200&c=7";

const _GAMES_RAW = [
  // ---- IO MULTIPLAYER / SHOOTERS (direct .io domains) ----
  { id: 1,  name: "Slither.io",          cat: "multiplayer", emoji: "🐍",  url: "https://slither.io/",                   featured: true  },
  { id: 2,  name: "Agar.io",             cat: "multiplayer", emoji: "🔵",  url: "https://agar.io/"                                           },
  { id: 3,  name: "Diep.io",             cat: "multiplayer", emoji: "🪖",  url: "https://diep.io/",                      featured: true  },
  { id: 4,  name: "Krunker.io",          cat: "shooting",    emoji: "🔫",  url: "https://krunker.io/",                   featured: true  },
  { id: 5,  name: "Shell Shockers",      cat: "shooting",    emoji: "🥚",  url: "https://shellshock.io/",                featured: true  },
  { id: 6,  name: "Venge.io",            cat: "shooting",    emoji: "🎯",  url: "https://venge.io/"                                          },
  { id: 7,  name: "1v1.LOL",             cat: "shooting",    emoji: "🏗️", url: "https://1v1.lol/",                      featured: true  },
  { id: 8,  name: "Bonk.io",             cat: "multiplayer", emoji: "💥",  url: "https://bonk.io/",                                          unity: true },
  { id: 9,  name: "Smash Karts",         cat: "racing",      emoji: "🏎️", url: "https://smashkarts.io/",                featured: true,  unity: true },
  { id: 10, name: "Skribbl.io",          cat: "multiplayer", emoji: "🖌️", url: "https://skribbl.io/"                                        },
  { id: 11, name: "Gartic Phone",        cat: "multiplayer", emoji: "🎨",  url: "https://garticphone.com/"                                   },
  { id: 12, name: "Zombs Royale",        cat: "multiplayer", emoji: "🧟",  url: "https://zombsroyale.io/",               featured: true  },
  { id: 13, name: "Starblast.io",        cat: "multiplayer", emoji: "🚀",  url: "https://starblast.io/"                                      },
  { id: 14, name: "MooMoo.io",           cat: "multiplayer", emoji: "🐮",  url: "https://moomoo.io/"                                         },
  { id: 15, name: "Little Big Snake",    cat: "multiplayer", emoji: "🐉",  url: "https://littlebigsnake.com/"                                },
  { id: 16, name: "Wormate.io",          cat: "multiplayer", emoji: "🪱",  url: "https://wormate.io/"                                        },
  { id: 17, name: "Splix.io",            cat: "multiplayer", emoji: "🟦",  url: "https://splix.io/"                                          },
  { id: 18, name: "Deeeep.io",           cat: "multiplayer", emoji: "🐟",  url: "https://deeeep.io/"                                         },
  { id: 19, name: "Evades.io",           cat: "multiplayer", emoji: "💢",  url: "https://evades.io/"                                         },
  { id: 20, name: "Defly.io",            cat: "multiplayer", emoji: "🚁",  url: "https://defly.io/"                                          },
  { id: 21, name: "Mope.io",             cat: "multiplayer", emoji: "🦊",  url: "https://mope.io/"                                           },
  { id: 22, name: "EV.io",               cat: "shooting",    emoji: "🎮",  url: "https://ev.io/",                        featured: true  },
  { id: 23, name: "Narrow.One",          cat: "shooting",    emoji: "🏹",  url: "https://narrow.one/",                   featured: true,  unity: true },
  { id: 24, name: "GoBattle.io",         cat: "action",      emoji: "⚔️", url: "https://gobattle.io/",                                      unity: true },
  { id: 25, name: "Tribals.io",          cat: "strategy",    emoji: "🏕️", url: "https://tribals.io/",                                       unity: true },
  { id: 26, name: "Foes.io",             cat: "shooting",    emoji: "💀",  url: "https://foes.io/"                                           },
  { id: 27, name: "Doblons.io",          cat: "multiplayer", emoji: "⛵",  url: "https://doblons.io/"                                        },
  { id: 28, name: "Raaaaft.io",          cat: "multiplayer", emoji: "🛟",  url: "https://raaaa.io/"                                          },
  { id: 29, name: "Driftin.io",          cat: "racing",      emoji: "🏁",  url: "https://driftin.io/"                                        },
  { id: 30, name: "Territorial.io",      cat: "strategy",    emoji: "🗺️", url: "https://territorial.io/",               featured: true  },
  { id: 31, name: "Mini Royale 2",       cat: "shooting",    emoji: "👑",  url: "https://miniroyale2.io/",                                   unity: true },
  { id: 32, name: "FlyOrDie.io",         cat: "multiplayer", emoji: "🦅",  url: "https://flyordie.io/"                                       },
  { id: 33, name: "Yorg.io",             cat: "strategy",    emoji: "🛡️", url: "https://yorg.io/"                                           },
  { id: 34, name: "Generals.io",         cat: "strategy",    emoji: "♟️", url: "https://generals.io/"                                       },
  { id: 35, name: "Powerline.io",        cat: "multiplayer", emoji: "⚡",  url: "https://powerline.io/"                                      },
  { id: 36, name: "Wings.io",            cat: "multiplayer", emoji: "✈️", url: "https://wings.io/"                                          },
  { id: 37, name: "Wanderers.io",        cat: "strategy",    emoji: "🧙",  url: "https://wanderers.io/"                                      },
  { id: 38, name: "Arras.io",            cat: "multiplayer", emoji: "🛸",  url: "https://arras.io/"                                          },
  { id: 39, name: "Sploop.io",           cat: "multiplayer", emoji: "🪓",  url: "https://sploop.io/"                                         },
  { id: 40, name: "Gulper.io",           cat: "multiplayer", emoji: "🌀",  url: "https://gulper.io/"                                         },
  { id: 41, name: "Limax.io",            cat: "multiplayer", emoji: "🐌",  url: "https://limax.io/"                                          },
  { id: 42, name: "Snowball.io",         cat: "multiplayer", emoji: "❄️", url: "https://snowball.io/"                                       },
  { id: 43, name: "Zlap.io",             cat: "multiplayer", emoji: "🔨",  url: "https://zlap.io/"                                           },
  { id: 44, name: "Dynast.io",           cat: "multiplayer", emoji: "🏰",  url: "https://dynast.io/"                                         },
  { id: 45, name: "Supersnake.io",       cat: "multiplayer", emoji: "🐍",  url: "https://supersnake.io/"                                     },
  { id: 46, name: "Biteme.io",           cat: "multiplayer", emoji: "🦈",  url: "https://biteme.io/"                                         },
  { id: 47, name: "Swordbattle.io",      cat: "multiplayer", emoji: "🗡️", url: "https://swordbattle.io/"                                    },
  { id: 48, name: "Digdig.io",           cat: "multiplayer", emoji: "⛏️", url: "https://digdig.io/"                                         },
  { id: 49, name: "Spinz.io",            cat: "multiplayer", emoji: "🌪️", url: "https://spinz.io/"                                          },
  { id: 50, name: "Lordz2.io",           cat: "strategy",    emoji: "👑",  url: "https://lordz2.io/"                                         },
  { id: 51, name: "Voxiom.io",           cat: "shooting",    emoji: "🟫",  url: "https://voxiom.io/",                                        unity: true },
  { id: 52, name: "Stabfish.io",         cat: "multiplayer", emoji: "🐡",  url: "https://stabfish.io/"                                       },
  { id: 53, name: "Lordz.io",            cat: "strategy",    emoji: "🏯",  url: "https://www.lordz.io/"                                      },
  { id: 54, name: "Gota.io",             cat: "multiplayer", emoji: "🟣",  url: "https://gota.io/web/"                                       },
  { id: 55, name: "Pixelz.io",           cat: "multiplayer", emoji: "🟪",  url: "https://pixelz.io/"                                         },
  { id: 56, name: "Hexar.io",            cat: "multiplayer", emoji: "⬡",   url: "https://hexar.io/"                                          },
  { id: 57, name: "Hordes.io",           cat: "multiplayer", emoji: "🧝",  url: "https://hordes.io/"                                         },
  { id: 58, name: "Repuls.io",           cat: "shooting",    emoji: "🤖",  url: "https://repuls.io/",                                        unity: true },
  { id: 59, name: "Taming.io",           cat: "multiplayer", emoji: "🐺",  url: "https://taming.io/"                                         },
  { id: 60, name: "Mope2.io",            cat: "multiplayer", emoji: "🦒",  url: "https://mope2.io/"                                          },
  { id: 61, name: "Brutal.io",           cat: "multiplayer", emoji: "⚒️", url: "https://brutal.io/"                                         },
  { id: 62, name: "Curve Fever Pro",     cat: "multiplayer", emoji: "🐍",  url: "https://curvefever.pro/"                                    },
  { id: 63, name: "Junon.io",            cat: "multiplayer", emoji: "🌙",  url: "https://junon.io/"                                          },
  { id: 64, name: "Florr.io",            cat: "multiplayer", emoji: "🌸",  url: "https://florr.io/"                                          },

  // ---- GAMEFLARE EMBEDS (single-player favorites) ----
  { id: 65,  name: "Stickman Hook",        cat: "arcade",      emoji: "🪝",  url: "https://www.gameflare.com/embed/stickman-hook/",            featured: true  },
  { id: 66,  name: "Moto X3M",             cat: "racing",      emoji: "🏍️", url: "https://www.gameflare.com/embed/moto-x3m/",                 featured: true  },
  { id: 67,  name: "Vex 5",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-5/"                                                },
  { id: 68,  name: "Vex 6",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-6/"                                                },
  { id: 69,  name: "Vex 7",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-7/"                                                },
  { id: 70,  name: "Run 3",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/run-3/",                    featured: true  },
  { id: 71,  name: "Tomb Runner",          cat: "adventure",   emoji: "🏛️", url: "https://www.gameflare.com/embed/tomb-runner/"                                          },
  { id: 72,  name: "Short Life",           cat: "arcade",      emoji: "💀",  url: "https://www.gameflare.com/embed/short-life/"                                            },
  { id: 73,  name: "Short Life 2",         cat: "arcade",      emoji: "💀",  url: "https://www.gameflare.com/embed/short-life-2/"                                          },
  { id: 74,  name: "Subway Clash 3D",      cat: "shooting",    emoji: "🚇",  url: "https://www.gameflare.com/embed/subway-clash-3d/"                                        },
  { id: 75,  name: "Madalin Stunt Cars 2", cat: "racing",      emoji: "🚗",  url: "https://www.gameflare.com/embed/madalin-stunt-cars-2/"                                   },
  { id: 76,  name: "Cubes 2048.io",        cat: "puzzle",      emoji: "🟦",  url: "https://www.gameflare.com/embed/cubes-2048-io/"                                          },
  { id: 77,  name: "Bullet Force",         cat: "shooting",    emoji: "🔫",  url: "https://www.gameflare.com/embed/bullet-force/",                                          unity: true },
  { id: 78,  name: "Drift Hunters",        cat: "racing",      emoji: "🏎️", url: "https://www.gameflare.com/embed/drift-hunters/",            featured: true,  unity: true },
  { id: 79,  name: "Stickman Boost",       cat: "arcade",      emoji: "🥷",  url: "https://www.gameflare.com/embed/stickman-boost/"                                         },
  { id: 80,  name: "Master Chess",         cat: "puzzle",      emoji: "♟️", url: "https://www.gameflare.com/embed/master-chess/"                                            },
  { id: 81,  name: "8 Ball Billiards",     cat: "sports",      emoji: "🎱",  url: "https://www.gameflare.com/embed/8-ball-billiards-classic/"                               },
  { id: 82,  name: "Basketball Stars",     cat: "sports",      emoji: "🏀",  url: "https://www.gameflare.com/embed/basketball-stars/"                                       },
  { id: 83,  name: "Soccer Skills",        cat: "sports",      emoji: "⚽",  url: "https://www.gameflare.com/embed/soccer-skills-euro-cup-2021/"                            },
  { id: 84,  name: "Among Us",             cat: "multiplayer", emoji: "🚀",  url: "https://www.gameflare.com/embed/among-us/"                                               },
  { id: 85,  name: "Fall Guys",            cat: "multiplayer", emoji: "🏆",  url: "https://www.gameflare.com/embed/fall-guys/"                                              },
  { id: 86,  name: "Happy Wheels",         cat: "arcade",      emoji: "🚲",  url: "https://www.gameflare.com/embed/happy-wheels/",             featured: true  },
  { id: 87,  name: "Tank Trouble",         cat: "action",      emoji: "🪖",  url: "https://www.gameflare.com/embed/tank-trouble/"                                           },
  { id: 88,  name: "Stickman Fighter",     cat: "action",      emoji: "🥋",  url: "https://www.gameflare.com/embed/stickman-fighter-epic-battle/"                          },
  { id: 89,  name: "Geometry Dash",        cat: "arcade",      emoji: "🔺",  url: "https://www.gameflare.com/embed/geometry-dash/",            featured: true  },
  { id: 90,  name: "Cut the Rope",         cat: "puzzle",      emoji: "✂️", url: "https://www.gameflare.com/embed/cut-the-rope/"                                            },
  { id: 91,  name: "Slope",                cat: "arcade",      emoji: "🟢",  url: "https://www.gameflare.com/embed/slope/",                    featured: true  },
  { id: 92,  name: "Death Run 3D",         cat: "adventure",   emoji: "💀",  url: "https://www.gameflare.com/embed/death-run-3d/"                                           },
  { id: 93,  name: "Tunnel Rush",          cat: "arcade",      emoji: "🌀",  url: "https://www.gameflare.com/embed/tunnel-rush/"                                            },
  { id: 94,  name: "Drift Boss",           cat: "racing",      emoji: "🚙",  url: "https://www.gameflare.com/embed/drift-boss/"                                             },
  { id: 95,  name: "Eggy Car",             cat: "racing",      emoji: "🥚",  url: "https://www.gameflare.com/embed/eggy-car/"                                               },
  { id: 96,  name: "Drive Mad",            cat: "racing",      emoji: "🚛",  url: "https://www.gameflare.com/embed/drive-mad/"                                              },
  { id: 97,  name: "Retro Bowl",           cat: "sports",      emoji: "🏈",  url: "https://www.gameflare.com/embed/retro-bowl/",               featured: true  },
  { id: 98,  name: "Tiny Fishing",         cat: "arcade",      emoji: "🎣",  url: "https://www.gameflare.com/embed/tiny-fishing/"                                           },
  { id: 99,  name: "Idle Breakout",        cat: "arcade",      emoji: "🧱",  url: "https://www.gameflare.com/embed/idle-breakout/"                                          },
  { id: 100, name: "Doodle Jump",          cat: "arcade",      emoji: "🦘",  url: "https://www.gameflare.com/embed/doodle-jump/"                                            },
  { id: 101, name: "Stickman Climb 2",     cat: "arcade",      emoji: "🧗",  url: "https://www.gameflare.com/embed/stickman-climb-2/"                                       },
  { id: 102, name: "Iron Snout",           cat: "action",      emoji: "🐷",  url: "https://www.gameflare.com/embed/iron-snout/"                                             },
  { id: 103, name: "Rooftop Snipers",      cat: "shooting",    emoji: "🎯",  url: "https://www.gameflare.com/embed/rooftop-snipers/"                                        },
  { id: 104, name: "Stick Duel",           cat: "action",      emoji: "⚔️", url: "https://www.gameflare.com/embed/stick-duel-medieval-wars/"                                },
  { id: 105, name: "Getaway Shootout",     cat: "shooting",    emoji: "🚁",  url: "https://www.gameflare.com/embed/getaway-shootout/",                                       unity: true },
  { id: 106, name: "Ragdoll Archers",      cat: "action",      emoji: "🏹",  url: "https://www.gameflare.com/embed/ragdoll-archers/",                                        unity: true },
  { id: 123, name: "Pixel Warfare",        cat: "shooting",    emoji: "💥",  url: "https://www.gameflare.com/embed/pixel-warfare/",                                           unity: true },
  { id: 124, name: "Blocky Cars",          cat: "racing",      emoji: "🚗",  url: "https://www.gameflare.com/embed/blocky-cars/",                                               unity: true },
  { id: 125, name: "War Brokers",          cat: "shooting",    emoji: "🎖️", url: "https://www.warbrokers.io/",                featured: true,  unity: true },
  { id: 126, name: "Copter.io",            cat: "shooting",    emoji: "🚁",  url: "https://copter.io/",                      featured: true,  unity: true },
  { id: 127, name: "Survivor.io",          cat: "multiplayer", emoji: "🧟",  url: "https://survivor.io/",                     featured: true,  unity: true },
  { id: 128, name: "Hole.io",              cat: "multiplayer", emoji: "🕳️", url: "https://hole-io.com/",                     featured: true,  unity: true },
  { id: 129, name: "Paper.io 2",           cat: "multiplayer", emoji: "📄",  url: "https://paper-io.com/paperio2.htm",        featured: true,  unity: true },
  { id: 130, name: "Mini Royale 2",        cat: "shooting",    emoji: "👑",  url: "https://miniroyale2.io/",                                  unity: true },
  { id: 131, name: "Repuls.io",            cat: "shooting",    emoji: "🤖",  url: "https://repuls.io/",                      featured: true,  unity: true },
  { id: 132, name: "Build Royale",         cat: "shooting",    emoji: "🏗️", url: "https://buildroyale.io/",                  featured: true,  unity: true },
  { id: 133, name: "Pixel Gun 3D",         cat: "shooting",    emoji: "🔫",  url: "https://pixelgun3d.net/play/",          featured: true,  unity: true },
  { id: 134, name: "Blockpost",            cat: "shooting",    emoji: "🎯",  url: "https://blockpost.net/",                  featured: true,  unity: true },
  { id: 135, name: "Forward Assault",      cat: "shooting",    emoji: "⚔️", url: "https://forwardassault.io/",              featured: true,  unity: true },

  // ---- STANDALONE / OFFICIAL SITES ----
  { id: 136, name: "Chess (Lichess)",      cat: "puzzle",      emoji: "♟️", url: "https://lichess.org/",                  featured: true  },
  { id: 137, name: "Wordle",               cat: "puzzle",      emoji: "📝",  url: "https://www.nytimes.com/games/wordle/index.html"                                          },
  { id: 138, name: "Minecraft Classic",    cat: "adventure",   emoji: "⛏️", url: "https://classic.minecraft.net/",        featured: true,  unity: true },
  { id: 139, name: "Cookie Clicker",       cat: "strategy",    emoji: "🍪",  url: "https://orteil.dashnet.org/cookieclicker/"                                                },
  { id: 140, name: "2048",                 cat: "puzzle",      emoji: "🔢",  url: "https://play2048.co/"                                                                     },
  { id: 141, name: "Sandboxels",           cat: "puzzle",      emoji: "🧪",  url: "https://sandboxels.r74n.com/"                                                             },
  { id: 142, name: "The Powder Toy",       cat: "puzzle",      emoji: "💨",  url: "https://powdertoy.co.uk/"                                                                 },
  { id: 143, name: "Snake",                cat: "arcade",      emoji: "🐍",  url: "https://playsnake.org/"                                                                   },
  { id: 144, name: "Tetris",               cat: "puzzle",      emoji: "🟦",  url: "https://tetris.com/play-tetris"                                                           },
  { id: 145, name: "GeoGuessr Free",       cat: "puzzle",      emoji: "🌍",  url: "https://www.geoguessr.com/free"                                                           },
  { id: 146, name: "Town of Salem",        cat: "strategy",    emoji: "🕵️", url: "https://www.blankmediagames.com/TownOfSalem/"                                              },
  { id: 147, name: "Sketchful.io",         cat: "multiplayer", emoji: "✏️", url: "https://sketchful.io/"                                                                    },
  { id: 148, name: "Drawasaurus",          cat: "multiplayer", emoji: "🦖",  url: "https://www.drawasaurus.org/"                                                             },
  { id: 149, name: "Super Smash Flash 2",  cat: "action",      emoji: "👊",  url: "https://www.supersmashflash.com/play/ssf2/",                featured: true  },

  // ---- KBH GAMES ----
  { id: 150, name: "Friday Night Funkin'", cat: "rhythm",      emoji: "🎵",  url: "https://kbhgames.com/game/friday-night-funkin-web" },
  { id: 151, name: "Among Us Online",      cat: "multiplayer", emoji: "🚀",  url: "https://kbhgames.com/game/among-us-online-v3" },
  { id: 152, name: "Minecraft Classic",    cat: "adventure",   emoji: "⛏️", url: "https://kbhgames.com/game/minecraft-classic" },
  { id: 153, name: "Roblox",               cat: "multiplayer", emoji: "🎮",  url: "https://kbhgames.com/game/roblox-online" },
  { id: 154, name: "Fortnite",             cat: "shooting",    emoji: "🔫",  url: "https://kbhgames.com/game/fortnite-online" },
  { id: 155, name: "Subway Surfers",       cat: "arcade",      emoji: "🏃",  url: "https://kbhgames.com/game/subway-surfers" },
  { id: 156, name: "Temple Run",           cat: "arcade",      emoji: "🏛️", url: "https://kbhgames.com/game/temple-run-2" },
  { id: 157, name: "Angry Birds",          cat: "puzzle",      emoji: "🐦",  url: "https://kbhgames.com/game/angry-birds" },
  { id: 158, name: "Plants vs Zombies",    cat: "strategy",    emoji: "🌻",  url: "https://kbhgames.com/game/plants-vs-zombies" },
  { id: 159, name: "Cut the Rope",         cat: "puzzle",      emoji: "✂️", url: "https://kbhgames.com/game/cut-the-rope" },
  { id: 160, name: "Fruit Ninja",          cat: "arcade",      emoji: "🍉",  url: "https://kbhgames.com/game/fruit-ninja" },
  { id: 161, name: "Doodle Jump",          cat: "arcade",      emoji: "🦘",  url: "https://kbhgames.com/game/doodle-jump" },
  { id: 162, name: "Flappy Bird",          cat: "arcade",      emoji: "🐦",  url: "https://kbhgames.com/game/flappy-bird" },
  { id: 163, name: "Geometry Dash",        cat: "arcade",      emoji: "🔺",  url: "https://kbhgames.com/game/geometry-dash" },
  { id: 164, name: "Happy Wheels",         cat: "arcade",      emoji: "🚲",  url: "https://kbhgames.com/game/happy-wheels" },
  { id: 165, name: "Run 3",                cat: "arcade",      emoji: "🏃",  url: "https://kbhgames.com/game/run-3" },
  { id: 166, name: "Vex 5",                cat: "adventure",   emoji: "🏃",  url: "https://kbhgames.com/game/vex-5" },
  { id: 167, name: "Vex 6",                cat: "adventure",   emoji: "🏃",  url: "https://kbhgames.com/game/vex-6" },
  { id: 168, name: "Vex 7",                cat: "adventure",   emoji: "🏃",  url: "https://kbhgames.com/game/vex-7" },
  { id: 169, name: "Stickman Hook",        cat: "arcade",      emoji: "🪝",  url: "https://kbhgames.com/game/stickman-hook" },
  { id: 170, name: "Moto X3M",             cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/moto-x3m" },
  { id: 171, name: "Drift Hunters",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/drift-hunters" },
  { id: 172, name: "Madalin Stunt Cars 2", cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/madalin-stunt-cars-2" },
  { id: 173, name: "Bullet Force",         cat: "shooting",    emoji: "🔫",  url: "https://kbhgames.com/game/bullet-force" },
  { id: 174, name: "Shell Shockers",       cat: "shooting",    emoji: "🥚",  url: "https://kbhgames.com/game/shell-shockers" },
  { id: 175, name: "Krunker.io",           cat: "shooting",    emoji: "🔫",  url: "https://kbhgames.com/game/krunker" },
  { id: 176, name: "1v1.LOL",              cat: "shooting",    emoji: "🏗️", url: "https://kbhgames.com/game/1v1-lol" },
  { id: 177, name: "War Brokers",          cat: "shooting",    emoji: "🎖️", url: "https://kbhgames.com/game/war-brokers" },
  { id: 178, name: "Repuls.io",            cat: "shooting",    emoji: "🤖",  url: "https://kbhgames.com/game/repuls-io" },
  { id: 179, name: "Build Royale",         cat: "shooting",    emoji: "🏗️", url: "https://kbhgames.com/game/build-royale" },
  { id: 180, name: "Survivor.io",          cat: "multiplayer", emoji: "🧟",  url: "https://kbhgames.com/game/survivor-io" },
  { id: 181, name: "Hole.io",              cat: "multiplayer", emoji: "🕳️", url: "https://kbhgames.com/game/hole-io" },
  { id: 182, name: "Paper.io 2",           cat: "multiplayer", emoji: "📄",  url: "https://kbhgames.com/game/paper-io-2" },
  { id: 183, name: "Slither.io",           cat: "multiplayer", emoji: "🐍",  url: "https://kbhgames.com/game/slither-io" },
  { id: 184, name: "Agar.io",              cat: "multiplayer", emoji: "🔵",  url: "https://kbhgames.com/game/agar-io" },
  { id: 185, name: "Diep.io",              cat: "multiplayer", emoji: "🪖",  url: "https://kbhgames.com/game/diep-io" },
  { id: 186, name: "Bonk.io",              cat: "multiplayer", emoji: "💥",  url: "https://kbhgames.com/game/bonk-io" },
  { id: 187, name: "Smash Karts",          cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/smash-karts" },
  { id: 188, name: "Skribbl.io",           cat: "multiplayer", emoji: "🖌️", url: "https://kbhgames.com/game/skribbl-io" },
  { id: 189, name: "Gartic Phone",         cat: "multiplayer", emoji: "🎨",  url: "https://kbhgames.com/game/gartic-phone" },
  { id: 190, name: "Zombs Royale",         cat: "multiplayer", emoji: "🧟",  url: "https://kbhgames.com/game/zombs-royale" },
  { id: 191, name: "MooMoo.io",            cat: "multiplayer", emoji: "🐮",  url: "https://kbhgames.com/game/moomoo-io" },
  { id: 192, name: "Wormate.io",           cat: "multiplayer", emoji: "🪱",  url: "https://kbhgames.com/game/wormate-io" },
  { id: 193, name: "Little Big Snake",     cat: "multiplayer", emoji: "🐉",  url: "https://kbhgames.com/game/little-big-snake" },
  { id: 194, name: "Splix.io",             cat: "multiplayer", emoji: "🟦",  url: "https://kbhgames.com/game/splix-io" },
  { id: 195, name: "Deeeep.io",            cat: "multiplayer", emoji: "🐟",  url: "https://kbhgames.com/game/deeeep-io" },
  { id: 196, name: "Defly.io",             cat: "multiplayer", emoji: "🚁",  url: "https://kbhgames.com/game/defly-io" },
  { id: 197, name: "Mope.io",              cat: "multiplayer", emoji: "🦊",  url: "https://kbhgames.com/game/mope-io" },
  { id: 198, name: "Territorial.io",       cat: "strategy",    emoji: "🗺️", url: "https://kbhgames.com/game/territorial-io" },
  { id: 199, name: "FlyOrDie.io",          cat: "multiplayer", emoji: "🦅",  url: "https://kbhgames.com/game/flyordie-io" },
  { id: 200, name: "Yorg.io",              cat: "strategy",    emoji: "🛡️", url: "https://kbhgames.com/game/yorg-io" },
  { id: 201, name: "Generals.io",          cat: "strategy",    emoji: "♟️", url: "https://kbhgames.com/game/generals-io" },
  { id: 202, name: "Powerline.io",         cat: "multiplayer", emoji: "⚡",  url: "https://kbhgames.com/game/powerline-io" },
  { id: 203, name: "Wings.io",             cat: "multiplayer", emoji: "✈️", url: "https://kbhgames.com/game/wings-io" },
  { id: 204, name: "Wanderers.io",         cat: "strategy",    emoji: "🧙",  url: "https://kbhgames.com/game/wanderers-io" },
  { id: 205, name: "Arras.io",             cat: "multiplayer", emoji: "🛸",  url: "https://kbhgames.com/game/arras-io" },
  { id: 206, name: "Sploop.io",            cat: "multiplayer", emoji: "🪓",  url: "https://kbhgames.com/game/sploop-io" },
  { id: 207, name: "Gulper.io",            cat: "multiplayer", emoji: "🌀",  url: "https://kbhgames.com/game/gulper-io" },
  { id: 208, name: "Limax.io",             cat: "multiplayer", emoji: "🐌",  url: "https://kbhgames.com/game/limax-io" },
  { id: 209, name: "Snowball.io",          cat: "multiplayer", emoji: "❄️", url: "https://kbhgames.com/game/snowball-io" },
  { id: 210, name: "Zlap.io",              cat: "multiplayer", emoji: "🔨",  url: "https://kbhgames.com/game/zlap-io" },
  { id: 211, name: "Dynast.io",            cat: "multiplayer", emoji: "🏰",  url: "https://kbhgames.com/game/dynast-io" },
  { id: 212, name: "Supersnake.io",        cat: "multiplayer", emoji: "🐍",  url: "https://kbhgames.com/game/supersnake-io" },
  { id: 213, name: "Biteme.io",            cat: "multiplayer", emoji: "🦈",  url: "https://kbhgames.com/game/biteme-io" },
  { id: 214, name: "Swordbattle.io",       cat: "multiplayer", emoji: "🗡️", url: "https://kbhgames.com/game/swordbattle-io" },
  { id: 215, name: "Digdig.io",            cat: "multiplayer", emoji: "⛏️", url: "https://kbhgames.com/game/digdig-io" },
  { id: 216, name: "Spinz.io",             cat: "multiplayer", emoji: "🌪️", url: "https://kbhgames.com/game/spinz-io" },
  { id: 217, name: "Lordz2.io",            cat: "strategy",    emoji: "👑",  url: "https://kbhgames.com/game/lordz2-io" },
  { id: 218, name: "Voxiom.io",            cat: "shooting",    emoji: "🟫",  url: "https://kbhgames.com/game/voxiom-io" },
  { id: 219, name: "Stabfish.io",          cat: "multiplayer", emoji: "🐡",  url: "https://kbhgames.com/game/stabfish-io" },
  { id: 220, name: "Lordz.io",             cat: "strategy",    emoji: "🏯",  url: "https://kbhgames.com/game/lordz-io" },
  { id: 221, name: "Gota.io",              cat: "multiplayer", emoji: "🟣",  url: "https://kbhgames.com/game/gota-io" },
  { id: 222, name: "Pixelz.io",            cat: "multiplayer", emoji: "🟪",  url: "https://kbhgames.com/game/pixelz-io" },
  { id: 223, name: "Hexar.io",             cat: "multiplayer", emoji: "⬡",  url: "https://kbhgames.com/game/hexar-io" },
  { id: 224, name: "Hordes.io",            cat: "multiplayer", emoji: "🧝",  url: "https://kbhgames.com/game/hordes-io" },
  { id: 225, name: "Taming.io",            cat: "multiplayer", emoji: "🐺",  url: "https://kbhgames.com/game/taming-io" },
  { id: 226, name: "Mope2.io",             cat: "multiplayer", emoji: "🦒",  url: "https://kbhgames.com/game/mope2-io" },
  { id: 227, name: "Brutal.io",            cat: "multiplayer", emoji: "⚒️", url: "https://kbhgames.com/game/brutal-io" },
  { id: 228, name: "Junon.io",             cat: "multiplayer", emoji: "🌙",  url: "https://kbhgames.com/game/junon-io" },
  { id: 229, name: "Florr.io",             cat: "multiplayer", emoji: "🌸",  url: "https://kbhgames.com/game/florr-io" },
  { id: 230, name: "Starblast.io",         cat: "multiplayer", emoji: "🚀",  url: "https://kbhgames.com/game/starblast-io" },
  { id: 231, name: "Venge.io",             cat: "shooting",    emoji: "🎯",  url: "https://kbhgames.com/game/venge-io" },
  { id: 232, name: "EV.io",                cat: "shooting",    emoji: "🎮",  url: "https://kbhgames.com/game/ev-io" },
  { id: 233, name: "Narrow.One",           cat: "shooting",    emoji: "🏹",  url: "https://kbhgames.com/game/narrow-one" },
  { id: 234, name: "GoBattle.io",          cat: "action",      emoji: "⚔️", url: "https://kbhgames.com/game/gobattle-io" },
  { id: 235, name: "Tribals.io",           cat: "strategy",    emoji: "🏕️", url: "https://kbhgames.com/game/tribals-io" },
  { id: 236, name: "Foes.io",              cat: "shooting",    emoji: "💀",  url: "https://kbhgames.com/game/foes-io" },
  { id: 237, name: "Doblons.io",           cat: "multiplayer", emoji: "⛵",  url: "https://kbhgames.com/game/doblons-io" },
  { id: 238, name: "Raaaaft.io",           cat: "multiplayer", emoji: "🛟",  url: "https://kbhgames.com/game/raaaa-io" },
  { id: 239, name: "Driftin.io",           cat: "racing",      emoji: "🏁",  url: "https://kbhgames.com/game/driftin-io" },
  { id: 240, name: "Curve Fever Pro",      cat: "multiplayer", emoji: "🐍",  url: "https://kbhgames.com/game/curve-fever-pro" },
  { id: 241, name: "Short Life",           cat: "arcade",      emoji: "💀",  url: "https://kbhgames.com/game/short-life" },
  { id: 242, name: "Short Life 2",         cat: "arcade",      emoji: "💀",  url: "https://kbhgames.com/game/short-life-2" },
  { id: 243, name: "Subway Clash 3D",      cat: "shooting",    emoji: "🚇",  url: "https://kbhgames.com/game/subway-clash-3d" },
  { id: 244, name: "Cubes 2048.io",        cat: "puzzle",      emoji: "🟦",  url: "https://kbhgames.com/game/cubes-2048-io" },
  { id: 245, name: "Stickman Boost",       cat: "arcade",      emoji: "🥷",  url: "https://kbhgames.com/game/stickman-boost" },
  { id: 246, name: "Master Chess",         cat: "puzzle",      emoji: "♟️", url: "https://kbhgames.com/game/master-chess" },
  { id: 247, name: "8 Ball Billiards",     cat: "sports",      emoji: "🎱",  url: "https://kbhgames.com/game/8-ball-billiards-classic" },
  { id: 248, name: "Basketball Stars",     cat: "sports",      emoji: "🏀",  url: "https://kbhgames.com/game/basketball-stars" },
  { id: 249, name: "Soccer Skills",        cat: "sports",      emoji: "⚽",  url: "https://kbhgames.com/game/soccer-skills-euro-cup-2021" },
  { id: 250, name: "Fall Guys",            cat: "multiplayer", emoji: "🏆",  url: "https://kbhgames.com/game/fall-guys" },
  { id: 251, name: "Tank Trouble",         cat: "action",      emoji: "🪖",  url: "https://kbhgames.com/game/tank-trouble" },
  { id: 252, name: "Stickman Fighter",     cat: "action",      emoji: "🥋",  url: "https://kbhgames.com/game/stickman-fighter-epic-battle" },
  { id: 253, name: "Tunnel Rush",          cat: "arcade",      emoji: "🌀",  url: "https://kbhgames.com/game/tunnel-rush" },
  { id: 254, name: "Drift Boss",           cat: "racing",      emoji: "🚙",  url: "https://kbhgames.com/game/drift-boss" },
  { id: 255, name: "Eggy Car",             cat: "racing",      emoji: "🥚",  url: "https://kbhgames.com/game/eggy-car" },
  { id: 256, name: "Drive Mad",            cat: "racing",      emoji: "🚛",  url: "https://kbhgames.com/game/drive-mad" },
  { id: 257, name: "Retro Bowl",           cat: "sports",      emoji: "🏈",  url: "https://kbhgames.com/game/retro-bowl" },
  { id: 258, name: "Tiny Fishing",         cat: "arcade",      emoji: "🎣",  url: "https://kbhgames.com/game/tiny-fishing" },
  { id: 259, name: "Idle Breakout",        cat: "arcade",      emoji: "🧱",  url: "https://kbhgames.com/game/idle-breakout" },
  { id: 260, name: "Stickman Climb 2",     cat: "arcade",      emoji: "🧗",  url: "https://kbhgames.com/game/stickman-climb-2" },
  { id: 261, name: "Iron Snout",           cat: "action",      emoji: "🐷",  url: "https://kbhgames.com/game/iron-snout" },
  { id: 262, name: "Rooftop Snipers",      cat: "shooting",    emoji: "🎯",  url: "https://kbhgames.com/game/rooftop-snipers" },
  { id: 263, name: "Stick Duel",           cat: "action",      emoji: "⚔️", url: "https://kbhgames.com/game/stick-duel-medieval-wars" },
  { id: 264, name: "Getaway Shootout",     cat: "shooting",    emoji: "🚁",  url: "https://kbhgames.com/game/getaway-shootout" },
  { id: 265, name: "Ragdoll Archers",      cat: "action",      emoji: "🏹",  url: "https://kbhgames.com/game/ragdoll-archers" },
  { id: 266, name: "Pixel Warfare",        cat: "shooting",    emoji: "💥",  url: "https://kbhgames.com/game/pixel-warfare" },
  { id: 267, name: "Blocky Cars",          cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/blocky-cars" },
  { id: 268, name: "Copter.io",            cat: "shooting",    emoji: "🚁",  url: "https://kbhgames.com/game/copter-io" },
  { id: 269, name: "Mini Royale 2",        cat: "shooting",    emoji: "👑",  url: "https://kbhgames.com/game/mini-royale-2" },
  { id: 270, name: "Pixel Gun 3D",         cat: "shooting",    emoji: "🔫",  url: "https://kbhgames.com/game/pixel-gun-3d" },
  { id: 271, name: "Blockpost",            cat: "shooting",    emoji: "🎯",  url: "https://kbhgames.com/game/blockpost" },
  { id: 272, name: "Forward Assault",      cat: "shooting",    emoji: "⚔️", url: "https://kbhgames.com/game/forward-assault" },
  { id: 273, name: "Cookie Clicker",       cat: "strategy",    emoji: "🍪",  url: "https://kbhgames.com/game/cookie-clicker" },
  { id: 274, name: "2048",                 cat: "puzzle",      emoji: "🔢",  url: "https://kbhgames.com/game/2048" },
  { id: 275, name: "Sandboxels",           cat: "puzzle",      emoji: "🧪",  url: "https://kbhgames.com/game/sandboxels" },
  { id: 276, name: "The Powder Toy",       cat: "puzzle",      emoji: "💨",  url: "https://kbhgames.com/game/the-powder-toy" },
  { id: 277, name: "Snake",                cat: "arcade",      emoji: "🐍",  url: "https://kbhgames.com/game/snake" },
  { id: 278, name: "Tetris",               cat: "puzzle",      emoji: "🟦",  url: "https://kbhgames.com/game/tetris" },
  { id: 279, name: "GeoGuessr Free",       cat: "puzzle",      emoji: "🌍",  url: "https://kbhgames.com/game/geoguessr-free" },
  { id: 280, name: "Town of Salem",        cat: "strategy",    emoji: "🕵️", url: "https://kbhgames.com/game/town-of-salem" },
  { id: 281, name: "Sketchful.io",         cat: "multiplayer", emoji: "✏️", url: "https://kbhgames.com/game/sketchful-io" },
  { id: 282, name: "Drawasaurus",          cat: "multiplayer", emoji: "🦖",  url: "https://kbhgames.com/game/drawasaurus" },
  { id: 283, name: "Super Smash Flash 2",  cat: "action",      emoji: "👊",  url: "https://kbhgames.com/game/super-smash-flash-2" },
  { id: 284, name: "Chess (Lichess)",      cat: "puzzle",      emoji: "♟️", url: "https://kbhgames.com/game/chess-lichess" },
  { id: 285, name: "Wordle",               cat: "puzzle",      emoji: "📝",  url: "https://kbhgames.com/game/wordle" },
  { id: 286, name: "Tomb Runner",          cat: "adventure",   emoji: "🏛️", url: "https://kbhgames.com/game/tomb-runner" },
  { id: 287, name: "Death Run 3D",         cat: "adventure",   emoji: "💀",  url: "https://kbhgames.com/game/death-run-3d" },
  { id: 288, name: "Slope",                cat: "arcade",      emoji: "🟢",  url: "https://kbhgames.com/game/slope" },
  { id: 289, name: "Eggy Car",             cat: "racing",      emoji: "🥚",  url: "https://kbhgames.com/game/eggy-car-2" },
  { id: 290, name: "Moto X3M 2",            cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/moto-x3m-2" },
  { id: 291, name: "Moto X3M 3",            cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/moto-x3m-3" },
  { id: 292, name: "Moto X3M 4",            cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/moto-x3m-4" },
  { id: 293, name: "Moto X3M 5",            cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/moto-x3m-5" },
  { id: 294, name: "Moto X3M 6",            cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/moto-x3m-6" },
  { id: 295, name: "Drift Hunters 2",       cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/drift-hunters-2" },
  { id: 296, name: "Burnout Drift",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/burnout-drift" },
  { id: 297, name: "Burnout Drift 2",      cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/burnout-drift-2" },
  { id: 298, name: "Burnout Drift 3",      cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/burnout-drift-3" },
  { id: 299, name: "City Car Driving",     cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/city-car-driving" },
  { id: 300, name: "Parking Fury",         cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/parking-fury" },
  { id: 301, name: "Parking Fury 2",        cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/parking-fury-2" },
  { id: 302, name: "Parking Fury 3",        cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/parking-fury-3" },
  { id: 303, name: "Madalin Cars Multiplayer", cat: "racing",  emoji: "🚗",  url: "https://kbhgames.com/game/madalin-cars-multiplayer" },
  { id: 304, name: "Speed Racing Pro 2",    cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/speed-racing-pro-2" },
  { id: 305, name: "Turbo Racing 3",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/turbo-racing-3" },
  { id: 306, name: "Highway Racer",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/highway-racer" },
  { id: 307, name: "Highway Racer 3D",      cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/highway-racer-3d" },
  { id: 308, name: "Neon Race",            cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/neon-race" },
  { id: 309, name: "Super Drift 3D",       cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/super-drift-3d" },
  { id: 310, name: "Drift City",           cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/drift-city" },
  { id: 311, name: "3D Car Simulator",     cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/3d-car-simulator" },
  { id: 312, name: "Police Pursuit 2",      cat: "racing",      emoji: "🚓",  url: "https://kbhgames.com/game/police-pursuit-2" },
  { id: 313, name: "Street Race",          cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/street-race" },
  { id: 314, name: "Death Race",           cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/death-race" },
  { id: 315, name: "Racing Thunder",       cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/racing-thunder" },
  { id: 316, name: "Asphalt 8",            cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/asphalt-8" },
  { id: 317, name: "Need for Speed",       cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/need-for-speed" },
  { id: 318, name: "Real Racing 3",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/real-racing-3" },
  { id: 319, name: "Project Torque",       cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/project-torque" },
  { id: 320, name: "Crazy Racers",         cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/crazy-racers" },
  { id: 321, name: "Thundercars",          cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/thundercars" },
  { id: 322, name: "Raceway",              cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/raceway" },
  { id: 323, name: "Nitro Nation",         cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/nitro-nation" },
  { id: 324, name: "Drag Racing",          cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/drag-racing" },
  { id: 325, name: "Street Racing",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/street-racing-2" },
  { id: 326, name: "Motor Wars",           cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/motor-wars" },
  { id: 327, name: "Car Eats Car",         cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/car-eats-car" },
  { id: 328, name: "Car Eats Car 2",       cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/car-eats-car-2" },
  { id: 329, name: "Car Eats Car 3",       cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/car-eats-car-3" },
  { id: 330, name: "Car Eats Car Evil",     cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/car-eats-car-evil" },
  { id: 331, name: "Earn to Die",          cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/earn-to-die" },
  { id: 332, name: "Earn to Die 2",        cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/earn-to-die-2" },
  { id: 333, name: "Earn to Die 3",        cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/earn-to-die-3" },
  { id: 334, name: "Hill Climb Racing",    cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/hill-climb-racing" },
  { id: 335, name: "Hill Climb Racing 2",   cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/hill-climb-racing-2" },
  { id: 336, name: "Offroad Racers",       cat: "racing",      emoji: "🚗",  url: "https://kbhgames.com/game/offroad-racers" },
  { id: 337, name: "Dirt Rally",           cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/dirt-rally" },
  { id: 338, name: "Rally Point",          cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/rally-point" },
  { id: 339, name: "Rally Point 2",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/rally-point-2" },
  { id: 340, name: "Rally Point 3",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/rally-point-3" },
  { id: 341, name: "Rally Point 4",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/rally-point-4" },
  { id: 342, name: "Grand Prix Hero",      cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/grand-prix-hero" },
  { id: 343, name: "Grand Prix Go",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/grand-prix-go" },
  { id: 344, name: "Grand Prix Go 2",      cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/grand-prix-go-2" },
  { id: 345, name: "Grand Prix Hero 2",    cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/grand-prix-hero-2" },
  { id: 346, name: "Formula Racing",       cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/formula-racing" },
  { id: 347, name: "Formula Racer",        cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/formula-racer" },
  { id: 348, name: "Formula Racer 2012",   cat: "racing",      emoji: "🏎️", url: "https://kbhgames.com/game/formula-racer-2012" },
  { id: 349, name: "Superbike Racer",      cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/superbike-racer" },
  { id: 350, name: "Bike Racing",          cat: "racing",      emoji: "🏍️", url: "https://kbhgames.com/game/bike-racing" },
];

const GAMES = _GAMES_RAW.map((g) => ({ ...g, thumb: _thumb(g.name) }));
