// ============================================================
// UBG PRO — GAME LIBRARY
// Curated list of working games (NO crazygames URLs).
// Sources: direct .io domains, gameflare.com /embed/, lichess.org,
// classic.minecraft.net, nytimes wordle, play2048, sandboxels, etc.
// ============================================================

const _thumb = (name) =>
  "https://tse2.mm.bing.net/th?q=" +
  encodeURIComponent(name + " game thumbnail") +
  "&w=320&h=200&c=7";

const _GAMES_RAW = [
  // ---- IO MULTIPLAYER / SHOOTERS (direct .io domains) ----
  { id: 1,  name: "Slither.io",          cat: "multiplayer", emoji: "🐍",  url: "https://slither.io/",                   featured: true  },
  { id: 2,  name: "Agar.io",             cat: "multiplayer", emoji: "🔵",  url: "https://agar.io/"                                           },
  { id: 3,  name: "Diep.io",             cat: "multiplayer", emoji: "🪖",  url: "https://diep.io/",                      featured: true  },
  { id: 4,  name: "Krunker.io",          cat: "shooting",    emoji: "🔫",  url: "https://krunker.io/",                   featured: true  },
  { id: 5,  name: "Shell Shockers",      cat: "shooting",    emoji: "🥚",  url: "https://shellshock.io/",                featured: true  },
  { id: 6,  name: "Venge.io",            cat: "shooting",    emoji: "🎯",  url: "https://venge.io/"                                          },
  { id: 7,  name: "1v1.LOL",             cat: "shooting",    emoji: "🏗️", url: "https://1v1.lol/",                      featured: true  },
  { id: 8,  name: "Bonk.io",             cat: "multiplayer", emoji: "💥",  url: "https://bonk.io/",                                          unity: true },
  { id: 9,  name: "Smash Karts",         cat: "racing",      emoji: "🏎️", url: "https://smashkarts.io/",                featured: true,  unity: true },
  { id: 10, name: "Skribbl.io",          cat: "multiplayer", emoji: "🖌️", url: "https://skribbl.io/"                                        },
  { id: 11, name: "Gartic Phone",        cat: "multiplayer", emoji: "🎨",  url: "https://garticphone.com/"                                   },
  { id: 12, name: "Zombs Royale",        cat: "multiplayer", emoji: "🧟",  url: "https://zombsroyale.io/",               featured: true  },
  { id: 13, name: "Starblast.io",        cat: "multiplayer", emoji: "🚀",  url: "https://starblast.io/"                                      },
  { id: 14, name: "MooMoo.io",           cat: "multiplayer", emoji: "🐮",  url: "https://moomoo.io/"                                         },
  { id: 15, name: "Little Big Snake",    cat: "multiplayer", emoji: "🐉",  url: "https://littlebigsnake.com/"                                },
  { id: 16, name: "Wormate.io",          cat: "multiplayer", emoji: "🪱",  url: "https://wormate.io/"                                        },
  { id: 17, name: "Splix.io",            cat: "multiplayer", emoji: "🟦",  url: "https://splix.io/"                                          },
  { id: 18, name: "Deeeep.io",           cat: "multiplayer", emoji: "🐟",  url: "https://deeeep.io/"                                         },
  { id: 19, name: "Evades.io",           cat: "multiplayer", emoji: "💢",  url: "https://evades.io/"                                         },
  { id: 20, name: "Defly.io",            cat: "multiplayer", emoji: "🚁",  url: "https://defly.io/"                                          },
  { id: 21, name: "Mope.io",             cat: "multiplayer", emoji: "🦊",  url: "https://mope.io/"                                           },
  { id: 22, name: "EV.io",               cat: "shooting",    emoji: "🎮",  url: "https://ev.io/",                        featured: true  },
  { id: 23, name: "Narrow.One",          cat: "shooting",    emoji: "🏹",  url: "https://narrow.one/",                   featured: true,  unity: true },
  { id: 24, name: "GoBattle.io",         cat: "action",      emoji: "⚔️", url: "https://gobattle.io/",                                      unity: true },
  { id: 25, name: "Tribals.io",          cat: "strategy",    emoji: "🏕️", url: "https://tribals.io/",                                       unity: true },
  { id: 26, name: "Foes.io",             cat: "shooting",    emoji: "💀",  url: "https://foes.io/"                                           },
  { id: 27, name: "Doblons.io",          cat: "multiplayer", emoji: "⛵",  url: "https://doblons.io/"                                        },
  { id: 28, name: "Raaaaft.io",          cat: "multiplayer", emoji: "🛟",  url: "https://raaaa.io/"                                          },
  { id: 29, name: "Driftin.io",          cat: "racing",      emoji: "🏁",  url: "https://driftin.io/"                                        },
  { id: 30, name: "Territorial.io",      cat: "strategy",    emoji: "🗺️", url: "https://territorial.io/",               featured: true  },
  { id: 31, name: "Mini Royale 2",       cat: "shooting",    emoji: "👑",  url: "https://miniroyale2.io/",                                   unity: true },
  { id: 32, name: "FlyOrDie.io",         cat: "multiplayer", emoji: "🦅",  url: "https://flyordie.io/"                                       },
  { id: 33, name: "Yorg.io",             cat: "strategy",    emoji: "🛡️", url: "https://yorg.io/"                                           },
  { id: 34, name: "Generals.io",         cat: "strategy",    emoji: "♟️", url: "https://generals.io/"                                       },
  { id: 35, name: "Powerline.io",        cat: "multiplayer", emoji: "⚡",  url: "https://powerline.io/"                                      },
  { id: 36, name: "Wings.io",            cat: "multiplayer", emoji: "✈️", url: "https://wings.io/"                                          },
  { id: 37, name: "Wanderers.io",        cat: "strategy",    emoji: "🧙",  url: "https://wanderers.io/"                                      },
  { id: 38, name: "Arras.io",            cat: "multiplayer", emoji: "🛸",  url: "https://arras.io/"                                          },
  { id: 39, name: "Sploop.io",           cat: "multiplayer", emoji: "🪓",  url: "https://sploop.io/"                                         },
  { id: 40, name: "Gulper.io",           cat: "multiplayer", emoji: "🌀",  url: "https://gulper.io/"                                         },
  { id: 41, name: "Limax.io",            cat: "multiplayer", emoji: "🐌",  url: "https://limax.io/"                                          },
  { id: 42, name: "Snowball.io",         cat: "multiplayer", emoji: "❄️", url: "https://snowball.io/"                                       },
  { id: 43, name: "Zlap.io",             cat: "multiplayer", emoji: "🔨",  url: "https://zlap.io/"                                           },
  { id: 44, name: "Dynast.io",           cat: "multiplayer", emoji: "🏰",  url: "https://dynast.io/"                                         },
  { id: 45, name: "Supersnake.io",       cat: "multiplayer", emoji: "🐍",  url: "https://supersnake.io/"                                     },
  { id: 46, name: "Biteme.io",           cat: "multiplayer", emoji: "🦈",  url: "https://biteme.io/"                                         },
  { id: 47, name: "Swordbattle.io",      cat: "multiplayer", emoji: "🗡️", url: "https://swordbattle.io/"                                    },
  { id: 48, name: "Digdig.io",           cat: "multiplayer", emoji: "⛏️", url: "https://digdig.io/"                                         },
  { id: 49, name: "Spinz.io",            cat: "multiplayer", emoji: "🌪️", url: "https://spinz.io/"                                          },
  { id: 50, name: "Lordz2.io",           cat: "strategy",    emoji: "👑",  url: "https://lordz2.io/"                                         },
  { id: 51, name: "Voxiom.io",           cat: "shooting",    emoji: "🟫",  url: "https://voxiom.io/",                                        unity: true },
  { id: 52, name: "Stabfish.io",         cat: "multiplayer", emoji: "🐡",  url: "https://stabfish.io/"                                       },
  { id: 53, name: "Lordz.io",            cat: "strategy",    emoji: "🏯",  url: "https://www.lordz.io/"                                      },
  { id: 54, name: "Gota.io",             cat: "multiplayer", emoji: "🟣",  url: "https://gota.io/web/"                                       },
  { id: 55, name: "Pixelz.io",           cat: "multiplayer", emoji: "🟪",  url: "https://pixelz.io/"                                         },
  { id: 56, name: "Hexar.io",            cat: "multiplayer", emoji: "⬡",   url: "https://hexar.io/"                                          },
  { id: 57, name: "Hordes.io",           cat: "multiplayer", emoji: "🧝",  url: "https://hordes.io/"                                         },
  { id: 58, name: "Repuls.io",           cat: "shooting",    emoji: "🤖",  url: "https://repuls.io/",                                        unity: true },
  { id: 59, name: "Taming.io",           cat: "multiplayer", emoji: "🐺",  url: "https://taming.io/"                                         },
  { id: 60, name: "Mope2.io",            cat: "multiplayer", emoji: "🦒",  url: "https://mope2.io/"                                          },
  { id: 61, name: "Brutal.io",           cat: "multiplayer", emoji: "⚒️", url: "https://brutal.io/"                                         },
  { id: 62, name: "Curve Fever Pro",     cat: "multiplayer", emoji: "🐍",  url: "https://curvefever.pro/"                                    },
  { id: 63, name: "Junon.io",            cat: "multiplayer", emoji: "🌙",  url: "https://junon.io/"                                          },
  { id: 64, name: "Florr.io",            cat: "multiplayer", emoji: "🌸",  url: "https://florr.io/"                                          },

  // ---- GAMEFLARE EMBEDS (single-player favorites) ----
  { id: 65,  name: "Stickman Hook",        cat: "arcade",      emoji: "🪝",  url: "https://www.gameflare.com/embed/stickman-hook/",            featured: true  },
  { id: 66,  name: "Moto X3M",             cat: "racing",      emoji: "🏍️", url: "https://www.gameflare.com/embed/moto-x3m/",                 featured: true  },
  { id: 67,  name: "Vex 5",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-5/"                                                },
  { id: 68,  name: "Vex 6",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-6/"                                                },
  { id: 69,  name: "Vex 7",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/vex-7/"                                                },
  { id: 70,  name: "Run 3",                cat: "adventure",   emoji: "🏃",  url: "https://www.gameflare.com/embed/run-3/",                    featured: true  },
  { id: 71,  name: "Tomb Runner",          cat: "adventure",   emoji: "🏛️", url: "https://www.gameflare.com/embed/tomb-runner/"                                          },
  { id: 72,  name: "Short Life",           cat: "arcade",      emoji: "💀",  url: "https://www.gameflare.com/embed/short-life/"                                            },
  { id: 73,  name: "Short Life 2",         cat: "arcade",      emoji: "💀",  url: "https://www.gameflare.com/embed/short-life-2/"                                          },
  { id: 74,  name: "Subway Clash 3D",      cat: "shooting",    emoji: "🚇",  url: "https://www.gameflare.com/embed/subway-clash-3d/"                                        },
  { id: 75,  name: "Madalin Stunt Cars 2", cat: "racing",      emoji: "🚗",  url: "https://www.gameflare.com/embed/madalin-stunt-cars-2/"                                   },
  { id: 76,  name: "Cubes 2048.io",        cat: "puzzle",      emoji: "🟦",  url: "https://www.gameflare.com/embed/cubes-2048-io/"                                          },
  { id: 77,  name: "Bullet Force",         cat: "shooting",    emoji: "🔫",  url: "https://www.gameflare.com/embed/bullet-force/",                                          unity: true },
  { id: 78,  name: "Drift Hunters",        cat: "racing",      emoji: "🏎️", url: "https://www.gameflare.com/embed/drift-hunters/",            featured: true,  unity: true },
  { id: 79,  name: "Stickman Boost",       cat: "arcade",      emoji: "🥷",  url: "https://www.gameflare.com/embed/stickman-boost/"                                         },
  { id: 80,  name: "Master Chess",         cat: "puzzle",      emoji: "♟️", url: "https://www.gameflare.com/embed/master-chess/"                                            },
  { id: 81,  name: "8 Ball Billiards",     cat: "sports",      emoji: "🎱",  url: "https://www.gameflare.com/embed/8-ball-billiards-classic/"                               },
  { id: 82,  name: "Basketball Stars",     cat: "sports",      emoji: "🏀",  url: "https://www.gameflare.com/embed/basketball-stars/"                                       },
  { id: 83,  name: "Soccer Skills",        cat: "sports",      emoji: "⚽",  url: "https://www.gameflare.com/embed/soccer-skills-euro-cup-2021/"                            },
  { id: 84,  name: "Among Us",             cat: "multiplayer", emoji: "🚀",  url: "https://www.gameflare.com/embed/among-us/"                                               },
  { id: 85,  name: "Fall Guys",            cat: "multiplayer", emoji: "🏆",  url: "https://www.gameflare.com/embed/fall-guys/"                                              },
  { id: 86,  name: "Happy Wheels",         cat: "arcade",      emoji: "🚲",  url: "https://www.gameflare.com/embed/happy-wheels/",             featured: true  },
  { id: 87,  name: "Tank Trouble",         cat: "action",      emoji: "🪖",  url: "https://www.gameflare.com/embed/tank-trouble/"                                           },
  { id: 88,  name: "Stickman Fighter",     cat: "action",      emoji: "🥋",  url: "https://www.gameflare.com/embed/stickman-fighter-epic-battle/"                          },
  { id: 89,  name: "Geometry Dash",        cat: "arcade",      emoji: "🔺",  url: "https://www.gameflare.com/embed/geometry-dash/",            featured: true  },
  { id: 90,  name: "Cut the Rope",         cat: "puzzle",      emoji: "✂️", url: "https://www.gameflare.com/embed/cut-the-rope/"                                            },
  { id: 91,  name: "Slope",                cat: "arcade",      emoji: "🟢",  url: "https://www.gameflare.com/embed/slope/",                    featured: true  },
  { id: 92,  name: "Death Run 3D",         cat: "adventure",   emoji: "💀",  url: "https://www.gameflare.com/embed/death-run-3d/"                                           },
  { id: 93,  name: "Tunnel Rush",          cat: "arcade",      emoji: "🌀",  url: "https://www.gameflare.com/embed/tunnel-rush/"                                            },
  { id: 94,  name: "Drift Boss",           cat: "racing",      emoji: "🚙",  url: "https://www.gameflare.com/embed/drift-boss/"                                             },
  { id: 95,  name: "Eggy Car",             cat: "racing",      emoji: "🥚",  url: "https://www.gameflare.com/embed/eggy-car/"                                               },
  { id: 96,  name: "Drive Mad",            cat: "racing",      emoji: "🚛",  url: "https://www.gameflare.com/embed/drive-mad/"                                              },
  { id: 97,  name: "Retro Bowl",           cat: "sports",      emoji: "🏈",  url: "https://www.gameflare.com/embed/retro-bowl/",               featured: true  },
  { id: 98,  name: "Tiny Fishing",         cat: "arcade",      emoji: "🎣",  url: "https://www.gameflare.com/embed/tiny-fishing/"                                           },
  { id: 99,  name: "Idle Breakout",        cat: "arcade",      emoji: "🧱",  url: "https://www.gameflare.com/embed/idle-breakout/"                                          },
  { id: 100, name: "Doodle Jump",          cat: "arcade",      emoji: "🦘",  url: "https://www.gameflare.com/embed/doodle-jump/"                                            },
  { id: 101, name: "Stickman Climb 2",     cat: "arcade",      emoji: "🧗",  url: "https://www.gameflare.com/embed/stickman-climb-2/"                                       },
  { id: 102, name: "Iron Snout",           cat: "action",      emoji: "🐷",  url: "https://www.gameflare.com/embed/iron-snout/"                                             },
  { id: 103, name: "Rooftop Snipers",      cat: "shooting",    emoji: "🎯",  url: "https://www.gameflare.com/embed/rooftop-snipers/"                                        },
  { id: 104, name: "Stick Duel",           cat: "action",      emoji: "⚔️", url: "https://www.gameflare.com/embed/stick-duel-medieval-wars/"                                },
  { id: 105, name: "Getaway Shootout",     cat: "shooting",    emoji: "🚁",  url: "https://www.gameflare.com/embed/getaway-shootout/",                                       unity: true },
  { id: 106, name: "Ragdoll Archers",      cat: "action",      emoji: "🏹",  url: "https://www.gameflare.com/embed/ragdoll-archers/",                                        unity: true },
  { id: 123, name: "Pixel Warfare",        cat: "shooting",    emoji: "💥",  url: "https://www.gameflare.com/embed/pixel-warfare/",                                           unity: true },
  { id: 124, name: "Blocky Cars",          cat: "racing",      emoji: "🚗",  url: "https://www.gameflare.com/embed/blocky-cars/",                                               unity: true },
  { id: 125, name: "War Brokers",          cat: "shooting",    emoji: "🎖️", url: "https://www.warbrokers.io/",                featured: true,  unity: true },
  { id: 126, name: "Copter.io",            cat: "shooting",    emoji: "🚁",  url: "https://copter.io/",                      featured: true,  unity: true },
  { id: 127, name: "Survivor.io",          cat: "multiplayer", emoji: "🧟",  url: "https://survivor.io/",                     featured: true,  unity: true },
  { id: 128, name: "Hole.io",              cat: "multiplayer", emoji: "🕳️", url: "https://hole-io.com/",                     featured: true,  unity: true },
  { id: 129, name: "Paper.io 2",           cat: "multiplayer", emoji: "📄",  url: "https://paper-io.com/paperio2.htm",        featured: true,  unity: true },
  { id: 130, name: "Mini Royale 2",        cat: "shooting",    emoji: "👑",  url: "https://miniroyale2.io/",                                  unity: true },
  { id: 131, name: "Repuls.io",            cat: "shooting",    emoji: "🤖",  url: "https://repuls.io/",                      featured: true,  unity: true },
  { id: 132, name: "Build Royale",         cat: "shooting",    emoji: "🏗️", url: "https://buildroyale.io/",                  featured: true,  unity: true },
  { id: 133, name: "Pixel Gun 3D",         cat: "shooting",    emoji: "🔫",  url: "https://pixelgun3d.net/play/",          featured: true,  unity: true },
  { id: 134, name: "Blockpost",            cat: "shooting",    emoji: "🎯",  url: "https://blockpost.net/",                  featured: true,  unity: true },
  { id: 135, name: "Forward Assault",      cat: "shooting",    emoji: "⚔️", url: "https://forwardassault.io/",              featured: true,  unity: true },

  // ---- STANDALONE / OFFICIAL SITES ----
  { id: 136, name: "Chess (Lichess)",      cat: "puzzle",      emoji: "♟️", url: "https://lichess.org/",                  featured: true  },
  { id: 137, name: "Wordle",               cat: "puzzle",      emoji: "📝",  url: "https://www.nytimes.com/games/wordle/index.html"                                          },
  { id: 138, name: "Minecraft Classic",    cat: "adventure",   emoji: "⛏️", url: "https://classic.minecraft.net/",        featured: true,  unity: true },
  { id: 139, name: "Cookie Clicker",       cat: "strategy",    emoji: "🍪",  url: "https://orteil.dashnet.org/cookieclicker/"                                                },
  { id: 140, name: "2048",                 cat: "puzzle",      emoji: "🔢",  url: "https://play2048.co/"                                                                     },
  { id: 141, name: "Sandboxels",           cat: "puzzle",      emoji: "🧪",  url: "https://sandboxels.r74n.com/"                                                             },
  { id: 142, name: "The Powder Toy",       cat: "puzzle",      emoji: "💨",  url: "https://powdertoy.co.uk/"                                                                 },
  { id: 143, name: "Snake",                cat: "arcade",      emoji: "🐍",  url: "https://playsnake.org/"                                                                   },
  { id: 144, name: "Tetris",               cat: "puzzle",      emoji: "🟦",  url: "https://tetris.com/play-tetris"                                                           },
  { id: 145, name: "GeoGuessr Free",       cat: "puzzle",      emoji: "🌍",  url: "https://www.geoguessr.com/free"                                                           },
  { id: 146, name: "Town of Salem",        cat: "strategy",    emoji: "🕵️", url: "https://www.blankmediagames.com/TownOfSalem/"                                              },
  { id: 147, name: "Sketchful.io",         cat: "multiplayer", emoji: "✏️", url: "https://sketchful.io/"                                                                    },
  { id: 148, name: "Drawasaurus",          cat: "multiplayer", emoji: "🦖",  url: "https://www.drawasaurus.org/"                                                             },
  { id: 149, name: "Super Smash Flash 2",  cat: "action",      emoji: "👊",  url: "https://www.supersmashflash.com/play/ssf2/",                featured: true  },

  // ---- POKI GAMES (actual embeds) ----
  { id: 150, name: "Subway Surfers",       cat: "arcade",      emoji: "🏃",  url: "https://poki.com/en/subway-surfers" },
  { id: 151, name: "Temple Run 2",         cat: "arcade",      emoji: "🏛️", url: "https://poki.com/en/temple-run-2" },
  { id: 152, name: "Moto X3M",             cat: "racing",      emoji: "🏍️", url: "https://poki.com/en/moto-x3m" },
  { id: 153, name: "Stickman Hook",        cat: "arcade",      emoji: "🪝",  url: "https://poki.com/en/stickman-hook" },
  { id: 154, name: "Venge.io",             cat: "shooting",    emoji: "🎯",  url: "https://poki.com/en/venge-io" },
  { id: 155, name: "Minecraft Classic",    cat: "adventure",   emoji: "⛏️", url: "https://poki.com/en/minecraft-classic" },
  { id: 156, name: "Bullet Force",         cat: "shooting",    emoji: "🔫",  url: "https://poki.com/en/bullet-force" },
  { id: 157, name: "Madalin Stunt Cars 2", cat: "racing",      emoji: "🚗",  url: "https://poki.com/en/madalin-stunt-cars-2" },
  { id: 158, name: "Drift Hunters",        cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/drift-hunters" },
  { id: 159, name: "Sushi Party",          cat: "multiplayer", emoji: "🍣",  url: "https://poki.com/en/sushi-party" },
  { id: 160, name: "Uno Online",           cat: "strategy",    emoji: "🃏",  url: "https://poki.com/en/uno-online" },
  { id: 161, name: "Who Is?",              cat: "puzzle",      emoji: "❓",  url: "https://poki.com/en/who-is" },
  { id: 162, name: "Brain Test",           cat: "puzzle",      emoji: "🧠",  url: "https://poki.com/en/brain-test" },
  { id: 163, name: "Brain Test 2",         cat: "puzzle",      emoji: "🧠",  url: "https://poki.com/en/brain-test-2" },
  { id: 164, name: "MooMoo.io",            cat: "multiplayer", emoji: "🐮",  url: "https://poki.com/en/moomoo-io" },
  { id: 165, name: "Slither.io",           cat: "multiplayer", emoji: "🐍",  url: "https://poki.com/en/slither-io" },
  { id: 166, name: "Paper.io 2",           cat: "multiplayer", emoji: "📄",  url: "https://poki.com/en/paper-io-2" },
  { id: 167, name: "Agar.io",              cat: "multiplayer", emoji: "🔵",  url: "https://poki.com/en/agar-io" },
  { id: 168, name: "Diep.io",              cat: "multiplayer", emoji: "🪖",  url: "https://poki.com/en/diep-io" },
  { id: 169, name: "Hole.io",              cat: "multiplayer", emoji: "🕳️", url: "https://poki.com/en/hole-io" },
  { id: 170, name: "City Car Driving",     cat: "racing",      emoji: "🚗",  url: "https://poki.com/en/city-car-driving-stunt-master" },
  { id: 171, name: "Parking Fury",         cat: "racing",      emoji: "🚗",  url: "https://poki.com/en/parking-fury" },
  { id: 172, name: "Parking Fury 2",        cat: "racing",      emoji: "🚗",  url: "https://poki.com/en/parking-fury-2" },
  { id: 173, name: "Parking Fury 3D",       cat: "racing",      emoji: "🚗",  url: "https://poki.com/en/parking-fury-3d" },
  { id: 174, name: "3D Car Simulator",     cat: "racing",      emoji: "🚗",  url: "https://poki.com/en/3d-car-simulator" },
  { id: 175, name: "Burnout Drift",        cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/burnout-drift" },
  { id: 176, name: "Burnout Drift 2",      cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/burnout-drift-2" },
  { id: 177, name: "Burnout Drift 3",      cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/burnout-drift-3" },
  { id: 178, name: "Highway Racer",        cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/highway-racer" },
  { id: 179, name: "Speed Racing Pro 2",    cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/speed-racing-pro-2" },
  { id: 180, name: "Madalin Cars Multiplayer", cat: "racing",  emoji: "🚗",  url: "https://poki.com/en/madalin-cars-multiplayer" },
  { id: 181, name: "Neon Race",            cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/neon-race" },
  { id: 182, name: "Super Drift 3D",       cat: "racing",      emoji: "🏎️", url: "https://poki.com/en/super-drift-3d" },
  { id: 183, name: "Eggy Car",             cat: "racing",      emoji: "🥚",  url: "https://poki.com/en/eggy-car" },
  { id: 184, name: "Drive Mad",            cat: "racing",      emoji: "🚛",  url: "https://poki.com/en/drive-mad" },
  { id: 185, name: "Tiny Fishing",         cat: "arcade",      emoji: "🎣",  url: "https://poki.com/en/tiny-fishing" },
  { id: 186, name: "Idle Breakout",        cat: "arcade",      emoji: "🧱",  url: "https://poki.com/en/idle-breakout" },
  { id: 187, name: "Stickman Climb 2",     cat: "arcade",      emoji: "🧗",  url: "https://poki.com/en/stickman-climb-2" },
  { id: 188, name: "Iron Snout",           cat: "action",      emoji: "🐷",  url: "https://poki.com/en/iron-snout" },
  { id: 189, name: "Rooftop Snipers",      cat: "shooting",    emoji: "🎯",  url: "https://poki.com/en/rooftop-snipers" },
  { id: 190, name: "Stick Duel",           cat: "action",      emoji: "⚔️", url: "https://poki.com/en/stick-duel" },
  { id: 191, name: "Getaway Shootout",     cat: "shooting",    emoji: "🚁",  url: "https://poki.com/en/getaway-shootout" },
  { id: 192, name: "Ragdoll Archers",      cat: "action",      emoji: "🏹",  url: "https://poki.com/en/ragdoll-archers" },
  { id: 193, name: "Short Life",           cat: "arcade",      emoji: "💀",  url: "https://poki.com/en/short-life" },
  { id: 194, name: "Short Life 2",         cat: "arcade",      emoji: "💀",  url: "https://poki.com/en/short-life-2" },
  { id: 195, name: "Tunnel Rush",          cat: "arcade",      emoji: "🌀",  url: "https://poki.com/en/tunnel-rush" },
  { id: 196, name: "Slope",                cat: "arcade",      emoji: "🟢",  url: "https://poki.com/en/slope" },
  { id: 197, name: "Drift Boss",           cat: "racing",      emoji: "🚙",  url: "https://poki.com/en/drift-boss" },
  { id: 198, name: "Retro Bowl",           cat: "sports",      emoji: "🏈",  url: "https://poki.com/en/retro-bowl" },
  { id: 199, name: "Basketball Stars",     cat: "sports",      emoji: "🏀",  url: "https://poki.com/en/basketball-stars" },
  { id: 200, name: "Soccer Skills",        cat: "sports",      emoji: "⚽",  url: "https://poki.com/en/soccer-skills-euro-cup" },
  { id: 201, name: "8 Ball Billiards",     cat: "sports",      emoji: "🎱",  url: "https://poki.com/en/8-ball-billiards-classic" },
  { id: 202, name: "Master Chess",         cat: "puzzle",      emoji: "♟️", url: "https://poki.com/en/master-chess" },
  { id: 203, name: "Lichess",              cat: "puzzle",      emoji: "♟️", url: "https://poki.com/en/lichess" },
  { id: 204, name: "2048",                 cat: "puzzle",      emoji: "🔢",  url: "https://poki.com/en/2048" },
  { id: 205, name: "Cubes 2048.io",        cat: "puzzle",      emoji: "🟦",  url: "https://poki.com/en/cubes-2048-io" },
  { id: 206, name: "Wordle",               cat: "puzzle",      emoji: "📝",  url: "https://poki.com/en/wordle" },
  { id: 207, name: "Cookie Clicker",       cat: "strategy",    emoji: "🍪",  url: "https://poki.com/en/cookie-clicker" },
  { id: 208, name: "Sandboxels",           cat: "puzzle",      emoji: "🧪",  url: "https://poki.com/en/sandboxels" },
  { id: 209, name: "The Powder Toy",       cat: "puzzle",      emoji: "💨",  url: "https://poki.com/en/the-powder-toy" },
  { id: 210, name: "Snake",                cat: "arcade",      emoji: "🐍",  url: "https://poki.com/en/snake" },
  { id: 211, name: "Tetris",               cat: "puzzle",      emoji: "🟦",  url: "https://poki.com/en/tetris" },
  { id: 212, name: "Solitaire",            cat: "puzzle",      emoji: "🃏",  url: "https://poki.com/en/solitaire" },
  { id: 213, name: "FreeCell",             cat: "puzzle",      emoji: "🃏",  url: "https://poki.com/en/freecell" },
  { id: 214, name: "Spider Solitaire",     cat: "puzzle",      emoji: "🃏",  url: "https://poki.com/en/spider-solitaire" },
  { id: 215, name: "Mahjong",              cat: "puzzle",      emoji: "🀄",  url: "https://poki.com/en/mahjong" },
  { id: 216, name: "Mahjong Dimensions",   cat: "puzzle",      emoji: "🀄",  url: "https://poki.com/en/mahjong-dimensions" },
  { id: 217, name: "Mahjong Connect",      cat: "puzzle",      emoji: "🀄",  url: "https://poki.com/en/mahjong-connect" },
  { id: 218, name: "Zuma",                 cat: "puzzle",      emoji: "🔮",  url: "https://poki.com/en/zuma" },
  { id: 219, name: "Bubble Shooter",       cat: "puzzle",      emoji: "🫧",  url: "https://poki.com/en/bubble-shooter" },
  { id: 220, name: "Candy Crush",          cat: "puzzle",      emoji: "🍬",  url: "https://poki.com/en/candy-crush" },
  { id: 221, name: "Bejeweled",            cat: "puzzle",      emoji: "💎",  url: "https://poki.com/en/bejeweled" },
  { id: 222, name: "Jewel Burst",          cat: "puzzle",      emoji: "💎",  url: "https://poki.com/en/jewel-burst" },
  { id: 223, name: "Gem 11",               cat: "puzzle",      emoji: "💎",  url: "https://poki.com/en/gem-11" },
  { id: 224, name: "Hex Puzzle",           cat: "puzzle",      emoji: "⬡",  url: "https://poki.com/en/hex-puzzle" },
  { id: 225, name: "Connect 4",            cat: "puzzle",      emoji: "🔴",  url: "https://poki.com/en/connect-4" },
  { id: 226, name: "Tic Tac Toe",          cat: "puzzle",      emoji: "⭕",  url: "https://poki.com/en/tic-tac-toe" },
  { id: 227, name: "Gobblet",              cat: "puzzle",      emoji: "🔵",  url: "https://poki.com/en/gobblet" },
  { id: 228, name: "Dots and Boxes",       cat: "puzzle",      emoji: "⬜",  url: "https://poki.com/en/dots-and-boxes" },
  { id: 229, name: "Battleship",           cat: "puzzle",      emoji: "⚓",  url: "https://poki.com/en/battleship" },
  { id: 230, name: "Checkers",             cat: "puzzle",      emoji: "⚫",  url: "https://poki.com/en/checkers" },
  { id: 231, name: "Draughts",             cat: "puzzle",      emoji: "⚫",  url: "https://poki.com/en/draughts" },
  { id: 232, name: "Reversi",              cat: "puzzle",      emoji: "⚫",  url: "https://poki.com/en/reversi" },
  { id: 233, name: "Othello",              cat: "puzzle",      emoji: "⚫",  url: "https://poki.com/en/othello" },
  { id: 234, name: "Go",                   cat: "puzzle",      emoji: "⚫",  url: "https://poki.com/en/go" },
  { id: 235, name: "Shogi",                cat: "puzzle",      emoji: "♟️", url: "https://poki.com/en/shogi" },
  { id: 236, name: "Xiangqi",              cat: "puzzle",      emoji: "♟️", url: "https://poki.com/en/xiangqi" },
  { id: 237, name: "Backgammon",           cat: "puzzle",      emoji: "🎲",  url: "https://poki.com/en/backgammon" },
  { id: 238, name: "Ludo",                 cat: "puzzle",      emoji: "🎲",  url: "https://poki.com/en/ludo" },
  { id: 239, name: "Snakes and Ladders",   cat: "puzzle",      emoji: "🐍",  url: "https://poki.com/en/snakes-and-ladders" },
  { id: 240, name: "Dominoes",             cat: "puzzle",      emoji: "🎲",  url: "https://poki.com/en/dominoes" },
  { id: 241, name: "Yahtzee",              cat: "puzzle",      emoji: "🎲",  url: "https://poki.com/en/yahtzee" },
  { id: 242, name: "Parchis",              cat: "puzzle",      emoji: "🎲",  url: "https://poki.com/en/parchis" },
  { id: 243, name: "Parqués",              cat: "puzzle",      emoji: "🎲",  url: "https://poki.com/en/parques" },
  { id: 244, name: "Parchís",              cat: "puzzle",      emoji: "🎲",  url: "https://poki.com/en/parchis" },

  // ---- COOLMATH GAMES ----
  { id: 245, name: "Run 3",                cat: "arcade",      emoji: "🏃",  url: "https://www.coolmathgames.com/0-run-3" },
  { id: 246, name: "Vex 5",                cat: "adventure",   emoji: "🏃",  url: "https://www.coolmathgames.com/0-vex-5" },
  { id: 247, name: "Vex 6",                cat: "adventure",   emoji: "🏃",  url: "https://www.coolmathgames.com/0-vex-6" },
  { id: 248, name: "Vex 7",                cat: "adventure",   emoji: "🏃",  url: "https://www.coolmathgames.com/0-vex-7" },
  { id: 249, name: "Fireboy and Watergirl", cat: "adventure",  emoji: "🔥",  url: "https://www.coolmathgames.com/0-fireboy-watergirl-forest-temple" },
  { id: 250, name: "Fireboy and Watergirl 2", cat: "adventure", emoji: "🔥",  url: "https://www.coolmathgames.com/0-fireboy-watergirl-2-light-temple" },
  { id: 251, name: "Fireboy and Watergirl 3", cat: "adventure", emoji: "🔥",  url: "https://www.coolmathgames.com/0-fireboy-watergirl-3-ice-temple" },
  { id: 252, name: "Fireboy and Watergirl 4", cat: "adventure", emoji: "🔥",  url: "https://www.coolmathgames.com/0-fireboy-watergirl-4-crystal-temple" },
  { id: 253, name: "Bob the Robber",        cat: "adventure",   emoji: "🦹",  url: "https://www.coolmathgames.com/0-bob-robber" },
  { id: 254, name: "Bob the Robber 2",      cat: "adventure",   emoji: "🦹",  url: "https://www.coolmathgames.com/0-bob-robber-2" },
  { id: 255, name: "Bob the Robber 3",      cat: "adventure",   emoji: "🦹",  url: "https://www.coolmathgames.com/0-bob-robber-3" },
  { id: 256, name: "Bob the Robber 4",      cat: "adventure",   emoji: "🦹",  url: "https://www.coolmathgames.com/0-bob-robber-4" },
  { id: 257, name: "Raft Wars",            cat: "shooting",    emoji: "🚣",  url: "https://www.coolmathgames.com/0-raft-wars" },
  { id: 258, name: "Raft Wars 2",          cat: "shooting",    emoji: "🚣",  url: "https://www.coolmathgames.com/0-raft-wars-2" },
  { id: 259, name: "Red Ball",             cat: "adventure",   emoji: "🔴",  url: "https://www.coolmathgames.com/0-red-ball" },
  { id: 260, name: "Red Ball 2",           cat: "adventure",   emoji: "🔴",  url: "https://www.coolmathgames.com/0-red-ball-2" },
  { id: 261, name: "Red Ball 3",           cat: "adventure",   emoji: "🔴",  url: "https://www.coolmathgames.com/0-red-ball-3" },
  { id: 262, name: "Red Ball 4",           cat: "adventure",   emoji: "🔴",  url: "https://www.coolmathgames.com/0-red-ball-4" },
  { id: 263, name: "Red Ball 5",           cat: "adventure",   emoji: "🔴",  url: "https://www.coolmathgames.com/0-red-ball-5" },
  { id: 264, name: "Papa's Pizzeria",      cat: "strategy",    emoji: "🍕",  url: "https://www.coolmathgames.com/0-papas-pizzeria" },
  { id: 265, name: "Papa's Burgeria",      cat: "strategy",    emoji: "🍔",  url: "https://www.coolmathgames.com/0-papas-burgeria" },
  { id: 266, name: "Papa's Taco Mia",      cat: "strategy",    emoji: "🌮",  url: "https://www.coolmathgames.com/0-papas-taco-mia" },
  { id: 267, name: "Papa's Freezeria",     cat: "strategy",    emoji: "🍦",  url: "https://www.coolmathgames.com/0-papas-freezeria" },
  { id: 268, name: "Papa's Pancakeria",    cat: "strategy",    emoji: "🥞",  url: "https://www.coolmathgames.com/0-papas-pancakeria" },
  { id: 269, name: "Papa's Wingeria",      cat: "strategy",    emoji: "🍗",  url: "https://www.coolmathgames.com/0-papas-wingeria" },
  { id: 270, name: "Papa's Cupcakeria",    cat: "strategy",    emoji: "🧁",  url: "https://www.coolmathgames.com/0-papas-cupcakeria" },
  { id: 271, name: "Papa's Hot Doggeria",  cat: "strategy",    emoji: "🌭",  url: "https://www.coolmathgames.com/0-papas-hot-doggeria" },
  { id: 272, name: "Papa's Donuteria",     cat: "strategy",    emoji: "🍩",  url: "https://www.coolmathgames.com/0-papas-donuteria" },
  { id: 273, name: "Papa's Cheeseria",     cat: "strategy",    emoji: "🧀",  url: "https://www.coolmathgames.com/0-papas-cheeseria" },
  { id: 274, name: "Papa's Bakeria",       cat: "strategy",    emoji: "🥧",  url: "https://www.coolmathgames.com/0-papas-bakeria" },
  { id: 275, name: "Papa's Sushiria",      cat: "strategy",    emoji: "🍣",  url: "https://www.coolmathgames.com/0-papas-sushiria" },
  { id: 276, name: "Papa's Scooperia",     cat: "strategy",    emoji: "🍨",  url: "https://www.coolmathgames.com/0-papas-scooperia" },
  { id: 277, name: "Papa's Pastaria",      cat: "strategy",    emoji: "🍝",  url: "https://www.coolmathgames.com/0-papas-pastaria" },
  { id: 278, name: "Papa's Mocharia",      cat: "strategy",    emoji: "☕",  url: "https://www.coolmathgames.com/0-papas-mocharia" },
  { id: 279, name: "Papa's Cluckeria",     cat: "strategy",    emoji: "🍗",  url: "https://www.coolmathgames.com/0-papas-cluckeria" },
  { id: 280, name: "Plants vs Zombies",    cat: "strategy",    emoji: "🌻",  url: "https://www.coolmathgames.com/0-plants-vs-zombies" },
  { id: 281, name: "Bloons Tower Defense", cat: "strategy",    emoji: "🐵",  url: "https://www.coolmathgames.com/0-bloons-tower-defense" },
  { id: 282, name: "Bloons TD 2",          cat: "strategy",    emoji: "🐵",  url: "https://www.coolmathgames.com/0-bloons-tower-defense-2" },
  { id: 283, name: "Bloons TD 3",          cat: "strategy",    emoji: "🐵",  url: "https://www.coolmathgames.com/0-bloons-tower-defense-3" },
  { id: 284, name: "Bloons TD 4",          cat: "strategy",    emoji: "🐵",  url: "https://www.coolmathgames.com/0-bloons-tower-defense-4" },
  { id: 285, name: "Bloons TD 5",          cat: "strategy",    emoji: "🐵",  url: "https://www.coolmathgames.com/0-bloons-tower-defense-5" },
  { id: 286, name: "Kingdom Rush",         cat: "strategy",    emoji: "🏰",  url: "https://www.coolmathgames.com/0-kingdom-rush" },
  { id: 287, name: "Kingdom Rush Frontiers", cat: "strategy",  emoji: "🏰",  url: "https://www.coolmathgames.com/0-kingdom-rush-frontiers" },
  { id: 288, name: "Kingdom Rush Origins", cat: "strategy",    emoji: "🏰",  url: "https://www.coolmathgames.com/0-kingdom-rush-origins" },
  { id: 289, name: "Kingdom Rush Vengeance", cat: "strategy",  emoji: "🏰",  url: "https://www.coolmathgames.com/0-kingdom-rush-vengeance" },
  { id: 290, name: "Duck Life",            cat: "adventure",   emoji: "🦆",  url: "https://www.coolmathgames.com/0-duck-life" },
  { id: 291, name: "Duck Life 2",          cat: "adventure",   emoji: "🦆",  url: "https://www.coolmathgames.com/0-duck-life-2" },
  { id: 292, name: "Duck Life 3",          cat: "adventure",   emoji: "🦆",  url: "https://www.coolmathgames.com/0-duck-life-3" },
  { id: 293, name: "Duck Life 4",          cat: "adventure",   emoji: "🦆",  url: "https://www.coolmathgames.com/0-duck-life-4" },
  { id: 294, name: "Duck Life 5",          cat: "adventure",   emoji: "🦆",  url: "https://www.coolmathgames.com/0-duck-life-5" },
  { id: 295, name: "Sugar, Sugar",         cat: "puzzle",      emoji: "🍬",  url: "https://www.coolmathgames.com/0-sugar-sugar" },
  { id: 296, name: "Sugar, Sugar 2",       cat: "puzzle",      emoji: "🍬",  url: "https://www.coolmathgames.com/0-sugar-sugar-2" },
  { id: 297, name: "Sugar, Sugar 3",       cat: "puzzle",      emoji: "🍬",  url: "https://www.coolmathgames.com/0-sugar-sugar-3" },
  { id: 298, name: "Chess",                cat: "puzzle",      emoji: "♟️", url: "https://www.coolmathgames.com/0-chess" },
  { id: 299, name: "Checkers",             cat: "puzzle",      emoji: "⚫",  url: "https://www.coolmathgames.com/0-checkers" },
  { id: 300, name: "Hangman",              cat: "puzzle",      emoji: "📝",  url: "https://www.coolmathgames.com/0-hangman" },
  { id: 301, name: "Sudoku",               cat: "puzzle",      emoji: "🔢",  url: "https://www.coolmathgames.com/0-sudoku" },
  { id: 302, name: "Kakuro",               cat: "puzzle",      emoji: "🔢",  url: "https://www.coolmathgames.com/0-kakuro" },
  { id: 303, name: "KenKen",               cat: "puzzle",      emoji: "🔢",  url: "https://www.coolmathgames.com/0-kenken" },
  { id: 304, name: "Nonograms",            cat: "puzzle",      emoji: "🖼️", url: "https://www.coolmathgames.com/0-nonograms" },
  { id: 305, name: "Picross",              cat: "puzzle",      emoji: "🖼️", url: "https://www.coolmathgames.com/0-picross" },
  { id: 306, name: "Lights Out",           cat: "puzzle",      emoji: "💡",  url: "https://www.coolmathgames.com/0-lights-out" },
  { id: 307, name: "Fruit Ninja",          cat: "arcade",      emoji: "🍉",  url: "https://www.coolmathgames.com/0-fruit-ninja" },
  { id: 308, name: "Cut the Rope",         cat: "puzzle",      emoji: "✂️", url: "https://www.coolmathgames.com/0-cut-the-rope" },
  { id: 309, name: "Cut the Rope 2",       cat: "puzzle",      emoji: "✂️", url: "https://www.coolmathgames.com/0-cut-the-rope-2" },
  { id: 310, name: "Cut the Rope 3",       cat: "puzzle",      emoji: "✂️", url: "https://www.coolmathgames.com/0-cut-the-rope-3" },
  { id: 311, name: "Angry Birds",          cat: "puzzle",      emoji: "🐦",  url: "https://www.coolmathgames.com/0-angry-birds" },
  { id: 312, name: "Angry Birds 2",        cat: "puzzle",      emoji: "🐦",  url: "https://www.coolmathgames.com/0-angry-birds-2" },
  { id: 313, name: "Flappy Bird",          cat: "arcade",      emoji: "🐦",  url: "https://www.coolmathgames.com/0-flappy-bird" },
  { id: 314, name: "Doodle Jump",          cat: "arcade",      emoji: "🦘",  url: "https://www.coolmathgames.com/0-doodle-jump" },
  { id: 315, name: "Happy Wheels",         cat: "arcade",      emoji: "🚲",  url: "https://www.coolmathgames.com/0-happy-wheels" },
  { id: 316, name: "QWOP",                 cat: "arcade",      emoji: "🏃",  url: "https://www.coolmathgames.com/0-qwop" },
  { id: 317, name: "GIRP",                 cat: "arcade",      emoji: "🧗",  url: "https://www.coolmathgames.com/0-girp" },
  { id: 318, name: "Cat Mario",            cat: "adventure",   emoji: "🐱",  url: "https://www.coolmathgames.com/0-cat-mario" },
  { id: 319, name: "The World's Hardest Game", cat: "arcade",  emoji: "😵",  url: "https://www.coolmathgames.com/0-the-worlds-hardest-game" },
  { id: 320, name: "The World's Hardest Game 2", cat: "arcade", emoji: "😵",  url: "https://www.coolmathgames.com/0-the-worlds-hardest-game-2" },
  { id: 321, name: "The World's Hardest Game 3", cat: "arcade", emoji: "😵",  url: "https://www.coolmathgames.com/0-the-worlds-hardest-game-3" },
  { id: 322, name: "The World's Hardest Game 4", cat: "arcade", emoji: "😵",  url: "https://www.coolmathgames.com/0-the-worlds-hardest-game-4" },
  { id: 323, name: "The Impossible Quiz",  cat: "puzzle",      emoji: "❓",  url: "https://www.coolmathgames.com/0-the-impossible-quiz" },
  { id: 324, name: "The Impossible Quiz 2", cat: "puzzle",      emoji: "❓",  url: "https://www.coolmathgames.com/0-the-impossible-quiz-2" },
  { id: 325, name: "The Impossible Quiz 3", cat: "puzzle",      emoji: "❓",  url: "https://www.coolmathgames.com/0-the-impossible-quiz-3" },
  { id: 326, name: "The Impossible Quiz 4", cat: "puzzle",      emoji: "❓",  url: "https://www.coolmathgames.com/0-the-impossible-quiz-4" },
  { id: 327, name: "Learn to Fly",         cat: "arcade",      emoji: "🐧",  url: "https://www.coolmathgames.com/0-learn-to-fly" },
  { id: 328, name: "Learn to Fly 2",       cat: "arcade",      emoji: "🐧",  url: "https://www.coolmathgames.com/0-learn-to-fly-2" },
  { id: 329, name: "Learn to Fly 3",       cat: "arcade",      emoji: "🐧",  url: "https://www.coolmathgames.com/0-learn-to-fly-3" },
  { id: 330, name: "Toss the Turtle",      cat: "arcade",      emoji: "🐢",  url: "https://www.coolmathgames.com/0-toss-the-turtle" },
  { id: 331, name: "Burrito Bison",        cat: "arcade",      emoji: "🌯",  url: "https://www.coolmathgames.com/0-burrito-bison" },
  { id: 332, name: "Burrito Bison Revenge", cat: "arcade",     emoji: "🌯",  url: "https://www.coolmathgames.com/0-burrito-bison-revenge" },
  { id: 333, name: "Burrito Bison Launcha Libre", cat: "arcade", emoji: "🌯",  url: "https://www.coolmathgames.com/0-burrito-bison-launcha-libre" },
  { id: 334, name: "Learn to Fly Idle",     cat: "arcade",      emoji: "🐧",  url: "https://www.coolmathgames.com/0-learn-to-fly-idle" },
  { id: 335, name: "Shopping Cart Hero",   cat: "arcade",      emoji: "🛒",  url: "https://www.coolmathgames.com/0-shopping-cart-hero" },
  { id: 336, name: "Shopping Cart Hero 2", cat: "arcade",      emoji: "🛒",  url: "https://www.coolmathgames.com/0-shopping-cart-hero-2" },
  { id: 337, name: "Shopping Cart Hero 3", cat: "arcade",      emoji: "🛒",  url: "https://www.coolmathgames.com/0-shopping-cart-hero-3" },
  { id: 338, name: "Hedgehog Launch",      cat: "arcade",      emoji: "🦔",  url: "https://www.coolmathgames.com/0-hedgehog-launch" },
  { id: 339, name: "Kitten Cannon",        cat: "arcade",      emoji: "🐱",  url: "https://www.coolmathgames.com/0-kitten-cannon" },
  { id: 340, name: "Penguin Launch",       cat: "arcade",      emoji: "🐧",  url: "https://www.coolmathgames.com/0-penguin-launch" },
  { id: 341, name: "Yeti Sports",          cat: "sports",      emoji: "❄️", url: "https://www.coolmathgames.com/0-yeti-sports" },
  { id: 342, name: "Yeti Sports 2",        cat: "sports",      emoji: "❄️", url: "https://www.coolmathgames.com/0-yeti-sports-2" },
  { id: 343, name: "Yeti Sports 3",        cat: "sports",      emoji: "❄️", url: "https://www.coolmathgames.com/0-yeti-sports-3" },
  { id: 344, name: "Yeti Sports 4",        cat: "sports",      emoji: "❄️", url: "https://www.coolmathgames.com/0-yeti-sports-4" },
];

const GAMES = _GAMES_RAW.map((g) => ({ ...g, thumb: _thumb(g.name) }));
